### ISSUE TITLE
Is Set-Privacy.bat just copied or copied and executed?

### ISSUE THREAD

**Issue by HarjitSi** [DrEmpiricism/Optimize-Offline#102]
Can you confirm that Set-Privacy.bat is not executed, just copied over. Then, after the installation, the user has to execute it by going to the directory and using an elevated prompt?

**Comment by DrEmpiricism** [comment]
Nothing gets applied and nothing is ran during Windows Setup and they are simply copied to the 'Setup\Scripts' folder for the Administrator to run if he/she so desires. They are placed there if the Administrator wants to manually modify and use them.
