### ISSUE TITLE
ReadMe Typos.

### ISSUE THREAD

**Issue by KedarWolf** [DrEmpiricism/Optimize-Offline#103]
I'm not trying to be a jerk, but I find the easiest way to find typos and grammar errors in any document is to register for a free Grammarly account and copy and paste the text there.

https://app.grammarly.com/

There are still a few typos and grammar errors when I did that, I was just curious though, as I saw you had corrected one.

**Comment by BenNottelling** [comment]
You can very easily submit a PR to update it

**Comment by DrEmpiricism** [comment]
This is honestly an irrelevant reason to open an 'issue.' 99% of the time I push the ReadMe from my phone, hence why it occasionally has typos or some redundancies, as I do a decent amount of traveling for my actual government job and do not have the time to open up my laptop just to push a ReadMe file.
