### ISSUE TITLE
Does The -Win32Calc Switch Work on Windows 18362?

### ISSUE THREAD

**Issue by KedarWolf** [DrEmpiricism/Optimize-Offline#104]
I ask because it's not being integrated into my Optimize-Offline 18362 ISO any more.

Below is my Start.cmd

```
@ECHO OFF
CD /D "%~dp0"

REM After setting the appropriate variables and switches, run this script as an administrator to quickly call Optimize-Offline.
REM A list of all available variables and switches can be found on Optimize-Offline's GitHub Repository.

REM Set the Optimize-Offline Source Path variable.
SET "SourcePath=D:\1\Enterprise.iso"

NET SESSION >NUL 2>&1
IF %ERRORLEVEL% NEQ 0 (
    ECHO Permission denied. This script must be run as an Administrator.
    ECHO:
    PAUSE
    EXIT
) ELSE (
    ECHO Running as Administrator.
    TIMEOUT /T 2 >NUL
    PowerShell.exe -NoProfile -ExecutionPolicy Bypass -File .\Optimize-Offline.ps1 -SourcePath "%SourcePath%" -WindowsApps "Select" -SystemApps -Packages -Features -Registry -Win32Calc -Additional -ISO
)
PAUSE
EXIT
```

**Comment by DrEmpiricism** [comment]
Is the WIM an en-US language? If not, the Win32Calc.wim will not integrate into the image because it only contains an en-US language package since it's a custom packaged WIM file.  Only build 17663 contains all the default language pack cabinet files.

And it integrates fine for me on 18362 and above.

**Comment by KedarWolf** [comment]
Oh, I use en-GB. :(

**Comment by KedarWolf** [comment]
Got old Calculator through Winaoro Tweaker, I knew it had an option to download it.

**Comment by DrEmpiricism** [comment]
When I have the time for it, I will create the packages for other languages.  The same goes for DaRT 10.

**Comment by KedarWolf** [comment]
Thank you.
