### ISSUE TITLE
Suggestion: Add to top of ChangeLog.md instead of replacing it completely

### ISSUE THREAD

**Issue by HarjitSi** [DrEmpiricism/Optimize-Offline#107]
As you create new versions, please consider adding the information to the beginning of the file. That way, there is a history that is visible without having to go spelunking through diffs.

Also, for each release, please consider adding your thoughts on the quality i.e. I would create and use a new image with this release; wait, I'm in the middle of something; etc.

I've been wanting to create a new image so I can start using my new machine and noticed you are cranking out some changes and so have been waiting for it to settle down. Unfortunately, I'm out of time, so am going ahead with release 3.2.6.4. 

Thanks for creating this and the effort you put in. It makes Windows useable because it removes so much cruft.

**Comment by DrEmpiricism** [comment]
The ChangeLog use to just have the updates appended do it but it ended up getting huge so I stopped. I suppose I can make it so it will archive past updated.
