### ISSUE TITLE
[Question, possible request] How do I apply group policies?

### ISSUE THREAD

**Issue by ImportTaste** [DrEmpiricism/Optimize-Offline#109]
Group policies seem to have some mystique around them. I used to think they were just alterations to the registry, but it seems like there's more to it than that. I made a file that would apply registry changes that correlated to what I found using a registry snapshot comparison tool from NirSoft called RegistryChangesView.

They did apply correctly, but the policies were not enabled. The only thing I could find in this area was a tool called [LGPO](https://blogs.technet.microsoft.com/secguide/2016/01/21/lgpo-exe-local-group-policy-object-utility-v1-0/) from Microsoft themselves, but it has some annoying limitations - for one thing you can't apply it to an offline image (except maybe if you made it part of a postinstall script?).

Could you give me some guidance on how to best apply policies to a Windows installation image? And if it's a pain in the ass, could you also implement a way to make it easier? I would really appreciate it because there is precious little information about doing this on search engine results. Thanks.

**Comment by DrEmpiricism** [comment]
The best way to deploy Group Policy is how we do it over a network using Windows Server where, in short terms, you make a backup of the GPO you want to deploy using LGPO and then parse the Registry.pol for both the User and Machine to a text file (again, using LGPO).  This text will contain every setting that is currently set in your Group Policy.  From here, you can optionally edit these text files and remove or edit any entries and then build a new Registry.pol out of that text file (again, using LGPO).  Finally, use LGPO to import the GPO settings into whatever device you want it set on and run gpupdate from an elevated command-prompt to update the policies on the system.

Moreover, deploying/importing security settings from the GPO requires the use of secedit which can often times be confusing, but the backup and import of a GPO is very simple with LGPO.

Are you simply trying to import the settings from GPO you already have configured, or also import security policies?

**Comment by ImportTaste** [comment]
Well, you described what I currently do, but I want to automate the process - making it part of the unattended installation I currently have configured. But I have not been able to figure out how to do it. Post-install setup scripts seem to run too early. I was hoping to make it a part of the installation image.

**Comment by DrEmpiricism** [comment]
Add it to a RunOnce key in the registry as these run after any post-install setup scripts in the 'Setup\Scripts' directory:

$KeyName = 'Run'
$Command = '%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\powershell.exe -ExecutionPolicy Bypass -File C:\Scripts\Run.ps1'
Set-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\RunOnce' -Name $KeyName -Value $Command -Type ExpandString

**Comment by ImportTaste** [comment]
Hey, that's smart thinking! Thanks.
