### ISSUE TITLE
[REQUEST] Allow more flexibility on 'install.wim' name for -SourcePath

### ISSUE THREAD

**Issue by MelkorLord** [DrEmpiricism/Optimize-Offline#112]
**Is your feature request related to a problem? Please describe.**
I have a WIM folder where there are a bunch of `install.wim` renamed according to their release (ie: `install_EnterpriseN_EN_17763.1.wim`, etc.). `Optimize-Offline` does not like that and insists on using `install.wim`.

**Describe the solution you'd like**
I've poked around the code in `Optimize-Offline.ps1` and here's what I've done: 

- Removed the `if/else` bloc, lines `229-236` and `250`
- Changed line `240` to : 
`Copy-Item -Path $($SourcePath.FullName) -Destination "$ImageFolder\install.wim"`

And now everything works fine without any trouble. I can name the `install.wim` whatever I want, it works flawlessly.

Could you consider making these changes?

Thank you.

**Comment by DrEmpiricism** [comment]
I will remove the initial 'install.wim' name requirement and just have Optimize-Offline rename the .wim once it has been copied.
