### ISSUE TITLE
[BUG] 3.2.6.9 - "The system cannot find the file specified." while dismounting.

### ISSUE THREAD

**Issue by iatethedinosaurs** [DrEmpiricism/Optimize-Offline#120]
**Describe the bug**
Error "The system cannot find the file specified." while attempting to dismount after applying optimizations.

**Desktop (please complete the following information):**
 - OS being optimized: Windows 10 LTSC
 - OS build: 17763

**Additional context**
Thought it could be an error with a space in my username, so I attempted it with the Image Dir and Optimize-Offline at C:. But still got the error.

_Previous version, 3.2.6.8, completes without error._

**Log files**
[Optimize-Offline.log](https://github.com/DrEmpiricism/Optimize-Offline/files/3566995/Optimize-Offline.log)

**Comment by DrEmpiricism** [comment]
Thank you for showing me this. It is not an issue on your part. Basically when I transferred all variables to the function, that included the variable the path where the boot image mounts so, to make this short, the primary script able to return a value for a mounted boot image despite a boot image not even being available to mount. The error you're receiving is occurring when it tries to dismount a non-existent boot image.

I will issue a code correction for this right now and you will be good to go.

**Comment by DrEmpiricism** [comment]
This has been corrected in the latest build.
