### ISSUE TITLE
Unable to load dll: unattend.dll

### ISSUE THREAD

**Issue by blueblood122** [DrEmpiricism/Optimize-Offline#122]
I am facing this issue with Windows 10 18362.329 and I am using that latest build Optimize-Offline v3.2.7.0 but there is no problem when using v3.2.6.9

Creating a Package Summary Log.
Post-Optimization Image Health State: [Healthy]
Saving and Dismounting Microsoft Windows Setup (x64)
Saving and Dismounting Microsoft Windows Recovery Environment (x64)
Rebuilding and Exporting Microsoft Windows Setup (x64)
Failed to Export Microsoft Windows Setup (x64)
Unable to load DLL 'unattend.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E) (System.DllNotFoundException,Microsoft.Dism.Commands.ExportWindowsImageCommand: F:\WINDOWS_10\Optimize-Offline-master\Optimize-Offline.ps1:1934 char:20)
Rebuilding and Exporting Microsoft Windows Recovery Environment (x64)
Failed to Export Microsoft Windows Recovery Environment (x64)
Unable to load DLL 'unattend.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E) (System.DllNotFoundException,Microsoft.Dism.Commands.ExportWindowsImageCommand: F:\WINDOWS_10\Optimize-Offline-master\Optimize-Offline.ps1:1962 char:16)
Saving and Dismounting Windows 10 Pro
Rebuilding and Exporting Windows 10 Pro using Fast compression.
Failed to Export Windows 10 Pro
Unable to load DLL 'unattend.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E) (System.DllNotFoundException,Microsoft.Dism.Commands.ExportWindowsImageCommand: F:\WINDOWS_10\Optimize-Offline-master\Optimize-Offline.ps1:2025 char:16)
Dismounting and discarding the image.
Press any key to continue . . . 

![Capture](https://user-images.githubusercontent.com/55019342/64473659-1daa4900-d187-11e9-995b-40a9ce6cc340.JPG)

**Comment by DrEmpiricism** [comment]
This is a message you get when you run PowerShell x86 on 64-bit Windows.

**Comment by blueblood122** [comment]
Ok but I am just running the start.cmd script which in turns runs powershell.. why would I be running poweshell x86

**Comment by blueblood122** [comment]
Issue not prevalent in the new version 3.2.7.1
