### ISSUE TITLE
[BUG] Duplicate line in Optimize-Offline.ps1 & Mistake (missing quote character) in Additional Tweaks.reg

### ISSUE THREAD

**Issue by Hyperyia** [DrEmpiricism/Optimize-Offline#124]
**Describe the bug**
Duplicate line in Optimize-Offline.ps1 & Mistake (missing quote character) in Additional Tweaks.reg

**Screenshots**
Duplicate line:

![image](https://user-images.githubusercontent.com/32967354/65334748-59033980-dbc3-11e9-95cf-c73ef78efb1f.png)

Mistake in .reg file:

![2019-09-20_16-21-09](https://user-images.githubusercontent.com/32967354/65334791-6f10fa00-dbc3-11e9-994f-9030b3f0117f.gif)

**Desktop (please complete the following information):**
 - OS being optimized: Windows 10 Enterprise LTSC 2019
 - OS build: 17763.1

**Additional context**
Duplicate line in Optimize-Offline.ps1 & Mistake (missing quote character) in Additional Tweaks.reg

**Log files**
N/A

**Comment by DrEmpiricism** [comment]
Thanks.
