### ISSUE TITLE
[REQUEST]Support for 1709

### ISSUE THREAD

**Issue by tharos96** [DrEmpiricism/Optimize-Offline#125]
Any chance 1709 will be supported?

**Comment by DrEmpiricism** [comment]
RS3 (1709) will likely never be supported because it has reached its EOL (end-of-life) and because of the kernel changes that were incorporated into builds 1803+.

**Comment by tharos96** [comment]
Could you share an old version that supports it? Basic features are enough for me.

**Comment by tharos96** [comment]
Would appreciate 1709 support so much!
