### ISSUE TITLE
Specifying what to remove in command line?

### ISSUE THREAD

**Issue by ImportTaste** [DrEmpiricism/Optimize-Offline#126]
I'm interested in removing everything in the `System Applications universally safe to remove` list via the command prompt in a way that doesn't require user interaction (i.e. a popup where I have to select each one individually). I notice that the command includes `-WindowsApps "Select"`, and I'm wondering if there is a way to modify that to specify what should be removed, and if so, what the syntax would be. For instance, `-WindowsApps "BioEnrollment CallingShellApp MicrosoftEdge MicrosoftEdgeDevToolsClient SecHealthUI ContentDeliveryManager ParentalControls SecureAssessmentBrowser XGpuEjectDialog XboxGameCallableUI"`

**Comment by DrEmpiricism** [comment]
The -WindowsApps parameter removes Provisioned Appx Packages, not System Apps.

The best way to incorporate what you're requesting is to do something similar to the -WindowsApps "Whitelist" feature where only System Applications added to that file are removed.

I had this enabled many versions ago and have been contemplating re-adding it (along with Whitelists for Capability Packages and Windows Features).

I will add this feature in an upcoming build.
