### ISSUE TITLE
[BUG] Mount-DiskImage : The parameter is incorrect

### ISSUE THREAD

**Issue by dgsharpe** [DrEmpiricism/Optimize-Offline#127]
Any attempt to run Optimize-Offline v3.2.7.4 produces an error when I run it.  I have also tried running Optimize-Offline on a clean installed virtual machine, but I get the same error.

ISO: `en_windows_10_enterprise_ltsc_2019_x64_dvd_74865958.iso`
SHA-1: `0b8476eff31f957590ade6fe671f16161037d3f6`

Error text:
```
Mount-DiskImage : A virtual disk support provider for the specified file was not found.
At C:\oo\Optimize-Offline.ps1:195 char:18
+ ... ISOMount = (Mount-DiskImage -ImagePath $SourcePath.FullName -StorageT ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (MSFT_DiskImage:ROOT/Microsoft/.../MSFT_DiskImage) [Mount-DiskImage], CimE
   xception
    + FullyQualifiedErrorId : HRESULT 0xc03a0014,Mount-DiskImage

WARNING: "w.iso" does not contain valid Windows Installation media.
Dismount-DiskImage : A virtual disk support provider for the specified file was not found.
At C:\oo\Optimize-Offline.ps1:200 char:16
+         [void](Dismount-DiskImage -ImagePath $SourcePath.FullName)
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (MSFT_DiskImage:ROOT/Microsoft/.../MSFT_DiskImage) [Dismount-DiskImage], C
   imException
    + FullyQualifiedErrorId : HRESULT 0xc03a0014,Dismount-DiskImage

Press any key to continue . . .```

**Comment by marcosviniciusf17** [comment]
You need to follow the bug reporting requirements.

**Comment by dgsharpe** [comment]
Reformatted:

**Describe the bug**
When I try to run Optimize-Offline.cmd with all the defaults (except obviously the ISO path), I immediately get the error posted below.

**Desktop:**
 - OS being optimized: Windows 10 LTSC
 - OS build: 17763.1 (Version 1809)

**Additional context**
I have tried running this on a fresh Windows 10 virtual machine, with the same results. I am running against an unmodified ISO, en_windows_10_enterprise_ltsc_2019_x64_dvd_74865958.iso with SHA-1 0b8476eff31f957590ade6fe671f16161037d3f6

**Log files**
```
Mount-DiskImage : A virtual disk support provider for the specified file was not found.
At C:\oo\Optimize-Offline.ps1:195 char:18
+ ... ISOMount = (Mount-DiskImage -ImagePath $SourcePath.FullName -StorageT ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (MSFT_DiskImage:ROOT/Microsoft/.../MSFT_DiskImage) [Mount-DiskImage], CimE
   xception
    + FullyQualifiedErrorId : HRESULT 0xc03a0014,Mount-DiskImage

WARNING: "w.iso" does not contain valid Windows Installation media.
Dismount-DiskImage : A virtual disk support provider for the specified file was not found.
At C:\oo\Optimize-Offline.ps1:200 char:16
+         [void](Dismount-DiskImage -ImagePath $SourcePath.FullName)
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (MSFT_DiskImage:ROOT/Microsoft/.../MSFT_DiskImage) [Dismount-DiskImage], C
   imException
    + FullyQualifiedErrorId : HRESULT 0xc03a0014,Dismount-DiskImage

Press any key to continue . . .
```

**Comment by DrEmpiricism** [comment]
What host OS are you running Optimize-Offline on?

Usually the error "A virtual disk support provider for the specified file was not found." occurs on a Windows Server environment or when there are Device Installation Restrictions set via Group Policy (i.e. new device installations are automatically blocked unless it's explicitly listed as an approved device). If this is the case, adding the ID "scsi\cdrommsft____virtual_dvd-rom_" to the list of approved will fix the issue.

**Comment by dgsharpe** [comment]
I'm running it on Windows 10 Pro build 17763. I have also tried running it in a virtual machine running a fresh install of Windows 10 LTSC 17763.1 . I get the same result on both.

None of the policies in Device Installation Restrictions were configured, but I enabled the Allowed list setting and added that id. The issue persists.
