### ISSUE TITLE
[REQUEST] Please clarify in README.md "Best Practice" RE: Feature updates

### ISSUE THREAD

**Issue by Phatastik** [DrEmpiricism/Optimize-Offline#131]
**Is your feature request related to a problem? Please describe.**
My, possibly mistaken, understanding is that the Optimize-Offline project is _only_ intended to prepare an image for a bare-metal install. 
I'm unclear if it's okay to apply a "feature update" AKA "semi-annual release" to a fully functioning OS built using Optimize-Offline.
**Describe the solution you'd like**
Please add content to the "Best Practice" section of the README.md clarifying whether it is acceptable to apply a future "feature update" to an existing online image built using the Optimize-Offline method or whether the only assured method is to download each new "semi-annual release" image, process the image using Optimize-Offline and then reinstall it onto a clean hard drive (perform a complete PC re-fresh). 
**A hypothetical example**
Apply Optimize-Offline to a fresh build image of 19H2
Bare-metal install Optimize-Offline treated 19H2 to my PC
Use (install apps, etc) Optimize-Offline treated 19H2 for 6 months
Microsoft releases 20H1
I want some feature only available in 20H1
(1) Option 1
Update in-place to 20H1
Continue to use PC with all Optimize-Offline benefits still intact?
or
(2) Option 2
Apply Optimize-Offline to a fresh build image of 20H1
Wipe my PC's system drive (including all installed apps)
Bare-metal install Optimize-Offline treated 20H1 to my PC
Re-install apps 
Use my re-freshed PC

**Comment by DrEmpiricism** [comment]
Though Optimize-Offline is designed for a bare-metal environment, it does not _require_ a bare-metal environment to function as it should.

As far as Feature Updates are concerned: no problems will arise from upgrading a current runtime environment that has been been optimized with Optimize-Offline to a new release; however, many of the optimizations will be reverted back to their default state. For example, removed System Applications and Appx Packages will be provisioned and installed during the update process.

What does work to circumvent this, is creating an optimized image of 20H1 and setting the optimized .wim image as the Reset Recovery Image. Then you can use the 'Reset this PC' feature which will will use the optimized .wim image as the recovery image as opposed to the OEM factory image. With this, you select the 'Keep my Files' option and Windows will be re-installed using the newly optimized .wim image and all your files will remain in-tact. I always set my original optimized .wim image as my Reset Recovery Image.

You can do this by creating a folder named 'ResetRecoveryImage' on a secondary drive, copying the optimized install.wim into the 'ResetRecoveryImage' folder, opening an elevated command-prompt and typing:

`reagentc /setosimage /path "Path\To\ResetRecoveryImage" /index 1`

So, if you created the folder 'ResetRecoveryImage' on your D-drive, the command would be:

`reagentc /setosimage /path "D:\ResetRecoveryImage" /index 1`

Once complete, I always set the 'ResetRecoveryImage' folder and install.wim to invisible, but it's not a requirement.

**Comment by Phatastik** [comment]
Thank you for your very clear "Optimize-update" guide! 
I'll try your suggested method to update an Optimized 1809 VM to 1909 (19H2).
