### ISSUE TITLE
[REQUEST] Remove flash player in 1909

### ISSUE THREAD

**Issue by plumch** [DrEmpiricism/Optimize-Offline#132]
Hello! 
I can not find solutions to completely remove adobe flash player in 1909 (18363.418)
After deleting the files associated with "adobe" from appdata, system32, syswow64, winsxs folders and cleaning the registry keys, the flash remains in the control panel and starts.  Please add a flash removal to the script. 
Thank you very much

**Comment by DrEmpiricism** [comment]
The Adobe Flash scheduled tasks first need to be deleted, followed by the Flash Player Update service, then you have to take ownership and remove the FlashUtil_ActiveX.exe and FlashUtil_ActiveX.dll files in the 'System32\Macromed\Flash' and 'SysWow64\Macromed\Flash' directories.
