### ISSUE TITLE
[BUG] Optimize-Offline cannot be run in a Preinstallation environment

### ISSUE THREAD

**Issue by LukasKysela** [DrEmpiricism/Optimize-Offline#133]
Script show message:
WARNING: Optimize-Offline cannot be run in a Preinstallation environment.

Why? Where is problem?

This is for 18363.418.191007-0143.19h2_release_svc_refresh_CLIENTBUSINESS_VOL_x64FRE_en-us.wim (error only)

Before: 18363.418.191007-0143.19h2_release_svc_refresh_CLIENTCONSUMER_RET_x64FRE_cs-cz.wim (no errors).
not have problems.

Same settings, same version script.

**Comment by DrEmpiricism** [comment]
The script checks if the path HKLM:\SYSTEM\CurrentControlSet\Control\MiniNT exists. If it does, it returns the error you're seeing and terminates the script. This error has nothing to do with the image being optimized but is determined by the OS environment the script is being run on.

If you're not trying to run Optimize-Offline in a preinstallation environment, then this registry key should not be present in the registry unless it was manually added.

**Comment by LukasKysela** [comment]
For both images, this message appears before copying the WIM file itself to the "temp" script folder. The image mount has not yet been mounted. Both images come from ESD format directly from Microsoft server and both are in actual version.
