### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by KedarWolf** [DrEmpiricism/Optimize-Offline#135]
**Describe the bug**
Unsigned drivers not being integrated.

**Desktop (please complete the following information):**

- Image Name: Windows 10 Enterprise
- Image Build: 1903

A few of my drivers I can apply with DISM are unsigned. I need them for my O/S, but on a clean install, I see they are not applied to my image with Optimize Offline

The switch I can use in DISM is:

`/ForceUnsigned`

**Comment by DrEmpiricism** [comment]
Optimize-Offline has always allowed the integration of unsigned drivers so long as an .inf file is present.

**Comment by KedarWolf** [comment]
Okay, it's a weird third party driver, might be ab issue.

But now I need to ask, can it be in a folder like Drivers/Install/Driver/ofnvme.inf or does it need to be in the root folder?

I use this switch so it gets all folders in the root folder.
`/recurse`
