### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by KedarWolf** [DrEmpiricism/Optimize-Offline#138]
**Describe the bug**
-DaRT "recovery" and "setup" does not work. Tried `-DaRT "recovery"` `-DaRT "setup"` and `-DaRT "setup', "recovery"`

**Desktop (please complete the following information):**

- Image Name: Windows Enterprise
- Image Build: 1903

**Additional content or data**

`Running as Administrator.
D:\Optimize-Offline-master\Optimize-Offline-master\Optimize-Offline.ps1 : A positional parameter cannot be found that
accepts argument 'recovery'.
    + CategoryInfo          : InvalidArgument: (:) [Optimize-Offline.ps1], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Optimize-Offline.ps1

Press any key to continue . . .
`

**Comment by DrEmpiricism** [comment]
-DaRT "Setup" = Works fine.
-DaRT "Recovery" = Works fine.
-DaRT "Setup", "Recovery" = Works fine.

![DaRT1](https://user-images.githubusercontent.com/20321974/68888644-561b5580-06e9-11ea-9fa7-2f3cc181fa9c.png)

![DaRT2](https://user-images.githubusercontent.com/20321974/68889439-e9a15600-06ea-11ea-95fa-8f443f52a364.png)

**Comment by KedarWolf** [comment]
I'll try to be more careful, I'm relatively new to GitHub and not really versed on these things.

I tried -DaRT "Setup" worked, -DaRT "Recovery" worked, but -DaRT "Setup", "Recovery" gives the below error.

`Running as Administrator.
D:\Optimize-Offline-master\Optimize-Offline-master\Optimize-Offline.ps1 : Cannot validate argument on parameter
'DaRT'. The argument "Setup," does not belong to the set "Setup,Recovery" specified by the ValidateSet attribute.
Supply an argument that is in the set and then try the command again.
    + CategoryInfo          : InvalidData: (:) [Optimize-Offline.ps1], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Optimize-Offline.ps1

Press any key to continue . . .`

Here is my .cmd file.

`@ECHO OFF
CD /D "%~dp0"
SET "WM_TITLE=Optimize-Offline"
SET "WM_VERSION=3.2.7.7"
TITLE %WM_TITLE% v%WM_VERSION%

REM After setting the appropriate variables and switches, run this script as an administrator to quickly call Optimize-Offline.
REM A list of all available variables and switches can be found on Optimize-Offline's GitHub Repository.

REM Set the Optimize-Offline Source Path variable.
SET "SourcePath=D:\1\Win10_18363.476_x64_2019-11-13.iso"

NET SESSION >NUL 2>&1
IF %ERRORLEVEL% NEQ 0 (
    ECHO Permission denied. This script must be run as an Administrator.
    ECHO:
    PAUSE
    EXIT
) ELSE (
    ECHO Running as Administrator.
    TIMEOUT /T 2 >NUL
    PowerShell.exe -NoProfile -ExecutionPolicy Bypass -File %~dpn0.ps1 -SourcePath "%SourcePath%" -WindowsApps "Select" -SystemApps -Capabilities -Packages -Features -Win32Calc -Registry -Additional -DaRT "Setup", "Recovery" -ISO "No-Prompt"
)
PAUSE
EXIT`

Two other people in the MyDigitalLife thread had the same issue.

Could it be because we downloaded the script from the Master page and not the Releases page?

brb, let me try it with the Releases version.

Actually, no, the Releases download gives the exact same error. I only thought maybe it was an issue because GitHub has produced a few script errors in the past.

**Comment by DrEmpiricism** [comment]
Releases should always be downloaded from the Releases page only. That version is always hash-checked when pushed and PGP signed because it's the package designed to be downloaded and used. Ocassionally there can be very slight differences between the packages release and the raw code in the master repository.

Anyways, by looking at the error (and I could be wrong), it appears as if the -DaRT parameter in the script you're using is not set as an array but as a string, hence why it's returning an error that the value does not belong to the ValidateSet. The -DaRT parameter should have a parameter that reads [String[]]$DaRT and NOT [String]$DaRT, which signifies it's an array parameter that will accept all values in the ValidateSet.

**Comment by DrEmpiricism** [comment]
EDIT - After checking it seems like the .cmd file is not passing the parameters property to the script and thus returning that error. Running it within the PowerShell console runs them fine, however.
