### ISSUE TITLE
[BUG] - registry 'tweaks' contained in own template.reg file not getting incorporated 

### ISSUE THREAD

**Issue by Phatastik** [DrEmpiricism/Optimize-Offline#139]
**Describe the bug**
Concise:  My six registry tweaks are incorporated into the image if I append them to the end of developer provided "Additional Tweaks.reg", but none of them were incorporated when I attempted to add them in a separate file named "My Additional Tweaks.reg". The 'Registry-Optimizations.log' indicated that both my .reg file and the developer provided one were successfully incorporated.
The 'append to' and the 'separate .reg file' tests were performed using an identical "Desktop"

**Desktop:**
- Image Name: [Windows 10 Education 1909]
- Image Build: [18363]
- Host Environment: [Windows 10 Education 1809]
- Test environment: VMWare 15.5
- Optimize-Offline Script version used: 3.2.7.7 

**Additional content or data**
Work-around is to continue to do as I've always done in the past which is to append my six registry tweak entries to the end of the entries in the developer provided "Additional Tweaks.reg," I was doing this before out of ignorance, but perhaps it was actually luck?

I have read, understand and appreciate the developer's response to "[REQUEST] DefaultMediaCost modification." None of my six registry tweaks require access to protected registry keys.

**Log files**
Relevant 'Registry-Optimizations.log' entries:
Importing Registry Template: "Additional Tweaks"
Importing Registry Template: "My Additional Tweaks"

**Comment by DrEmpiricism** [comment]
I have not had any issues importing multiple registry files using the 'RegistryTemplates' folder. Moreover, since it's not returning an error it means there was no error when the templates were imported. However, if there is an issue with importing a template due to permissions or the like, it will also not return an error.

Considering they import if you add them to the supplied 'Additional Tweaks.reg' file, permission issues are not a factor. What is the content of these registry templates you're trying to import?

**Comment by Phatastik** [comment]
I figured I'm doing something wrong, since your project is fully vetted/tested and used by many people who are not reporting issues.
#1
I was referring to the [other post](https://github.com/DrEmpiricism/Optimize-Offline/issues/136) to let you know that I had read your response, but I'm not the OP for that request. Meaning that I'm *not* the user who is trying to modify the protected 'DefaultMediaCost' key.
#2 
I redid a fresh Optimized image following my 'standard' append to the Additional Tweaks.reg procedure and all my changes were accepted.
My additions work when appended, but for whatever reason didn't work when I added them as a separate file. I don't believe any of them are a protected keys; however, if they are protected, they get applied correctly when appended.
My appended additions:
```
;************************************************************************************
;**************************** The 'My Tweaks' section ******************************
;************************************************************************************
; Set Windows Search service disabled
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\WSearch]
"Start"=dword:00000004

; Set Delivery Optimization service disabled
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\DoSvc]
"Start"=dword:00000004

; Remove OneDrive first run value
[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run]
"OneDriveSetup"=-

; Minimize sending diagnostic and usage data
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\WINEVT\Channels\Microsoft-Windows-Application-Experience/Program-Telemetry]
"Enabled"=dword:00000000
```

**Comment by ImportTaste** [comment]
@DrEmpiricism I just noticed something that might be useful. [NSudo is MIT license](https://github.com/M2Team/NSudo/blob/master/License.md) and does not trigger any virus detection despite being able to give applications such a high level of access (through both GUI and CLI). You could incorporate it into your project for the purposes of applying RegistryTemplates.

**Comment by Phatastik** [comment]
@ImportTaste If you follow @DrEmpiricism instructions and use the included capability of the Optimize-Offline project than you don't need to use a third party solution to accomplish what you suggest.
For example, to apply the 'DefaultMediaCost' key changes you requested in the [your post](https://github.com/DrEmpiricism/Optimize-Offline/issues/136) to an Optimized image all you need to do is add two lines of code to the "OOBE.cmd" file. Like so:
```
REG ADD HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\NetworkList\DefaultMediaCost /v Ethernet /t REG_DWORD /d 2 /f
REG ADD HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\NetworkList\DefaultMediaCost /v WiFi /t REG_DWORD /d 2 /f
```
Done!

**Comment by ImportTaste** [comment]
Honestly, I would much rather apply it directly to the registry hive than rely on a setup completion script that has to be clean itself up afterward.

**Comment by Phatastik** [comment]
@ImportTaste I can totally appreciate what you're saying and I used to do the same. If you're only adding a couple of registry values, than it's not too hard to maintain.
Armed with your skills at working with mounted reg Hives. . .  An alternative approach is to add a 'pause' code-line to the Optimize-Offline script in the "#region Registry Optimizations section" 
Than you can: 

- Do what you want with the mounted "WIM_HKLM_"
- Un-pause and let the script finish

`Read-Host -Prompt "Press Enter to continue"`

**Comment by Phatastik** [comment]
'Best practice' for me is to append my reg key changes to the existing Additional Tweaks.reg
