### ISSUE TITLE
[REQUEST] "Offline" Path/Partition Support

### ISSUE THREAD

**Issue by PureOcean** [DrEmpiricism/Optimize-Offline#149]
Offline-Image

> Does not perform any changes to an installed or live system nor can it optimize a live system.

Understand why you only support WIM and ISO files.

I just want to use the Offline-Image for already _extracted_ by DISM (or WinNTSetup) to another partiton Windows Image.

Three Option: "Offline" path that the **System Preparation** has not started yet.

Can you provide literally _**Offline-Image**_ support for Windows Image on disk partition If the System Preparation haven't _yet started_? 

> %Windir%\Setup\State\State.ini
> ImageState=**IMAGE_STATE_GENERALIZE_RESEAL_TO_OOBE**

**Comment by DrEmpiricism** [comment]
For your first question, are you referring to a captured image or just an image exported/extracted by DISM/WinNTSetup?

As for your second question - it could be optimized with Optimize-Offline with a few code changes. I have used Optimized-Offline on Hyper-V VHDX files before.

**Comment by PureOcean** [comment]
> For your first question, are you referring to a captured image or just an image exported/extracted by DISM/WinNTSetup?

I referred _just an image exported/extracted by DISM/WinNTSetup._ 
So no need to waste time opening and repackaging as WIM and/or ISO. Because the image already _extracted_.

> As for your second question - it could be optimized with Optimize-Offline with a few code changes. I have used Optimized-Offline on Hyper-V VHDX files before.

Also adding to VHD(x) support could be useful.
Four output support: ISO, WIM, Offline path/extracted image, VHD(x)

I hope, no need much effort for code changes.
Thank you for keep to improve **Optimize-Offline**.

**Comment by DrEmpiricism** [comment]
I will do some testing on this over the weekend.
