### ISSUE TITLE
Too many closing curly brackets are causing errors in $DisableTelemetry

### ISSUE THREAD

**Issue by Neomien** [DrEmpiricism/Optimize-Offline#15]
In v3.1.2.8 at line 2806 char 102 and at line 2807 char 128 there are unnecessary closing curly brackets.
Correct lines should be:
`PowerShell -Command "& { Get-NetFirewallRule | Where-Object DisplayGroup -EQ 'Delivery Optimization' | Remove-NetFirewallRule -ErrorAction SilentlyContinue }"`
and
`PowerShell -Command "& { Get-NetFirewallRule | Where-Object DisplayGroup -Like 'Windows Media Player Network Sharing Service*' | Remove-NetFirewallRule -ErrorAction SilentlyContinue }"`

**Comment by DrEmpiricism** [comment]
Thanks for pointing that out.  The additional closing brackets have been removed.
