### ISSUE TITLE
[BUG]- Cannot bind argument to parameter 'Path' because it is null with Optimize-Offline 4.0.0.4 and the same error with version 4.0.0.5

### ISSUE THREAD

**Issue by Phatastik** [DrEmpiricism/Optimize-Offline#157]
**Describe the bug**
Running Module : Optimize-Offline 4.0.0.4 and the same error is still present with version 4.0.0.5
(1)
Command ".\Start-Optimize.ps1" produces the error : "Cannot bind argument to parameter 'Path' because it is null"
If I repeat command ".\Start-Optimize.ps1" than the Optimize-Offline 4.0.0.4 script seems to perform correctly but ...
(2)
Produces a second error: "Failed to Import Custom App Associations" which leads to ...
(3)
Third error at the the end of script completion with producing the Export-ErrorLog "You cannot call a method on a null-valued expression"

**Images:**
Path error
https://ibb.co/NShv08K
Associations fail
https://ibb.co/5jQFvzs
Error log fail
https://ibb.co/vZM9vjw

**Please complete the following information:**
- Image Name: [Windows 10 Education] 
- Image Build: [18362] also tried on [14393]
- Host Environment: [Windows 10 Education 17763] also tried on [Windows 10 Enterprise 2016 LTSB]
- Parameters Passed: [ "WindowsApps": "Whitelist",  "SystemApps": true, "Win32Calc": true]

**Additional content or data**
Failed attempts were on a freshly booted PC.
Script host directory is a top directory on a second HDD
Shortening the script host directory name to "OO04" didn't make a difference

**Working with a WIM file**
Input and desired output is install.wim.
Input: install.wim
Output: optimized install.wim

**Log files**
Optimize-Offline.log shows "[ERROR]: Failed to Import Custom App Associations"
OptimizeErrors.log is blank

**Comment by strotee** [comment]
Trying installing ADK for 1903  and re-run the script.  https://go.microsoft.com/fwlink/?linkid=2086042

**Comment by Phatastik** [comment]
I'm processing a WIM.
Input: install.wim
Output: optimized install.wim.
I'll add some images to my post.

**Comment by DrEmpiricism** [comment]
For the 1st error, do you have a screenshot of the entire error record. I need to see the full error record to see where you're running into this issue.

**Comment by Phatastik** [comment]
@DrEmpiricism error free application of your newest scripts seem to depend on having ADK installed.  
I have just now successfully run version 4.0.0.5 of your script on a PC **with ADK installed.**

I resisted @strotee 's advice to install ADK since I'm working with a WIM file and not an ISO, but than I stumbled on a post by KedarWolf [https://forums.mydigitallife.net/threads/optimize-offline-guide-windows-debloating-tool-for-windows-1803-1903-19h2-1909-and-ltsc-2019.80038/page-13#post-1575953](url) that also recommends installing ADK. 

**On a PC without ADK Installed**
The script spits out an immediate error.
For clarity, install.wim is on a spare drive (F:\) with the script package in a folder named "O" (F:\O).

**The complete error pasted from the PowerShell console:**
`PS F:\O> .\Start-Optimize.ps1
.\Start-Optimize.ps1 : Cannot bind argument to parameter 'Path' because it is null.
At line:1 char:1
+ .\Start-Optimize.ps1
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (F:\O\Optimize-Offline.psm1:String) [], RuntimeException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Resolve-FullPath` 

**Images**
Error Image: https://ibb.co/7GqzMKf
Directory layout: https://ibb.co/Zcb1xhk

**Comment by ImportTaste** [comment]
In JSON, the backslash is an escape character, so you need to double them if you're not doing that already.

**Comment by DrEmpiricism** [comment]
https://github.com/DrEmpiricism/Optimize-Offline/issues/162#issuecomment-588601811
