### ISSUE TITLE
[BUG] Cannot call a method on a null valued expression

### ISSUE THREAD

**Issue by Alexusson** [DrEmpiricism/Optimize-Offline#159]
Hi, doc

I hope everything is at least fine on your side. Thank you for regularly updating this beautiful app...

With the last version 4.0.0.4, I am receiving an error  "you cannot call a method on a null valued expression" at the end of the script (see image here https://imgur.com/D318Md6) while the **Optimize error log is empty**. Does the message mean that one of the variables is not presented/have value NULL in the code? Is something missing?
I tried to run in VB, but I am getting BSOD after installing components, features, and updates finished.

On the other side version, 4.0.0.3 is working fine here.

Image Name: Windows 10 Enterprise 
Image Build: 18363.592
Host Environment: Windows 10 Enterprise LTSC 2019
Parameters Passed:   "WindowsApps", "Whitelist", "SystemApps": true, "Capabilities": true, "Packages": true, "Features": true, "DeveloperMode": false, "WindowsStore": false, "MicrosoftEdge": false,
  "Win32Calc": true, "Dedup": false, "Registry": true, "Additional": true, "ISO": "No-Prompt"

**Comment by Alexusson** [comment]
Meanwhile, I saw one other user have the same situation here https://github.com/DrEmpiricism/Optimize-Offline/issues/158

**Comment by DrEmpiricism** [comment]
This was an issue with the declared error object showing an error in the module (as the 1 error message reflects) but the function that exports the actual error itself not resolving an error, thus throwing an error when creating a custom object to detail said error(s).

The function that exports any logged error record objects has been updated in this latest build (4.0.0.5) to remedy this issue.

**Comment by Alexusson** [comment]
Hi, doc,

OK, thanks for the reply and the latest release. I have thought it is not a big deal, and I intended to inform you. I consider myself as a tester of your releases. ;) It is similar to the situation I had before when I been adding Windows folder inside "Content\Aditional\Wallpaper" and error showing a message: Windows folder already exists... Nothing crucial and each created ISO worked fine then...

... However, the same error is still prompting with version 4.0.0.5, and unfortunately, BSOD is showing with each version 4.x.x.x I tried (after finishing installation of components, features, and updates). The version that works without any issue on my side is 3.2.7.8. Why precisely that version? Because that is the latest version, I have stored on my laptop. Probably other newer versions 3.x.x.x would be worked fine too.

Cheers

**Comment by Alexusson** [comment]
Hi, doc

Nah, it does not matter... You can close this now. It was my mistake I am pretty sure. I do not chop Windows a lot but it was late and I probably removed additional package(s) in the Grid that is close to the packages I usually remove. Stupid fingers! Anyway, thanks for the fast reply!

I will try today again if something went wrong I will report here. Thanks for all you are doing...

More power to your brain and skills,...
Alexusson
