### ISSUE TITLE
[BUG] Builds the iso, log shows no errors, powershell does, iso won't install.

### ISSUE THREAD

**Issue by CarlosMerc** [DrEmpiricism/Optimize-Offline#160]
**Describe the bug**
I do things as I normally do. Nothing has changed on the system, don't run anything in the background, haven't changed params, latest version worked for me, then just stopped. Script runs through with no errors, everything looks fine, builds ISO but then this message appears after. Running ISO gives corrupt windows files:

Remove-Item : Cannot remove item C:\Windows\Logs\DISM\dism.log: The process cannot access the file 'C:\Windows\Logs\DISM\dism.log' 
because it is being used by another process.
At C:\kk\Src\Public\Remove-Container.ps1:22 char:49
+ ... th $Item) { Remove-Item -LiteralPath $Item -Recurse -Force -ErrorActi ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\Windows\Logs\DISM\dism.log:FileInfo) [Remove-Item], IOException
    + FullyQualifiedErrorId : RemoveFileSystemItemIOError,Microsoft.PowerShell.Commands.RemoveItemCommand 

**Please complete the following information:**

- Image Name: [Windows 10 LTSC]
- Image Build: [17763]
- Host Environment: [Windows 10 LTSC]
- Parameters Passed: 
"WindowsApps": "Select",
  "SystemApps": true,
  "Capabilities": true,
  "Packages": true,
  "Features": true,
  "DeveloperMode": false,
  "WindowsStore": false,
  "MicrosoftEdge": false,
  "Win32Calc": false,
  "Dedup": false,
  "Registry": false,
  "Additional": {
    "Setup": false,
    "Wallpaper": false,
    "SystemLogo": false,
    "LockScreen": false,
    "RegistryTemplates": true,
    "Unattend": false,
    "Drivers": false,
    "NetFx3": false
  },
  "ISO": "No-Prompt"

sfc and dism checkhealth/scanhealth/analyzecomponentstore don't turn up any issues.

**Comment by DrEmpiricism** [comment]
I ran Optimize-Offline with the exact same parameters as you and had no issues booting from the created no-prompt ISO and installing LTSC with said ISO.

That said, there also should be no errors when attempting to remove the DISM.log due to it "being used by another process" unless it's being accessed by another process outside of Optimize-Offline.

![ISO LTSC](https://user-images.githubusercontent.com/20321974/73698857-47bd5400-46b0-11ea-870e-1f7ab8e3724b.png)

**Comment by CarlosMerc** [comment]
I updated to new release, it all works again.
I did replace files before, not sure what the issue was.
