### ISSUE TITLE
[REQUEST] Remove the requirement to install Windows 10 Assessment and Deployment Kit (ADK)

### ISSUE THREAD

**Issue by Phatastik** [DrEmpiricism/Optimize-Offline#162]
**Is your feature request related to a problem? Please describe.**
Yes. Since version 4.0.0.4 of this project, unless I install Windows 10 Assessment and Deployment Kit (ADK) prior to running the "Start-Optimize.ps1" script, I get this [Bug] https://github.com/DrEmpiricism/Optimize-Offline/issues/157. 
There are others on a mydigitallife thread dedicated to this script who report having problems identical to [Bug] https://github.com/DrEmpiricism/Optimize-Offline/issues/157 and also install ADK as the working "solution." For example, here is a [recent (17 Feb 20) mydigitallife post](https://forums.mydigitallife.net/threads/optimize-offline-guide-windows-debloating-tool-for-windows-1803-1903-19h2-1909-and-ltsc-2019.80038/page-15#post-1578629) describing an issue identical [Bug] https://github.com/DrEmpiricism/Optimize-Offline/issues/157. In the [next post](https://forums.mydigitallife.net/threads/optimize-offline-guide-windows-debloating-tool-for-windows-1803-1903-19h2-1909-and-ltsc-2019.80038/page-15#post-1578677), the person claims success after using the ADK "solution" 

**Describe the solution you'd like**
Please allow this project to function independently of any "third-party" requirements. 
The last version I used prior to trying 4.0.0.4 that I know was free of any "Windows ADK requirement" was [Optimize-Offline 4.0.0.0](https://github.com/DrEmpiricism/Optimize-Offline/releases/tag/4.0.0.0). 

**Describe alternatives you've considered**
I move the recent versions of the Optimize-Offline package and the source WIM to a virtual machine dedicated to Microsoft Deployment Toolkit which has ADK installed. Then I successfully run the "Start-Optimize.ps1" script. Not an ideal solution for my use-case. 

**Additional context**
Other context and screenshots are shown in the above [Bug] link(s).

**Comment by DrEmpiricism** [comment]
There is no requirement for having an ADK installed. It simply checks if the ADK is installed and uses its Dism executable for commands the PowerShell Dism cmdlet does not support. If an ADK is not detected, however, it uses the system Dism executable located in the 'Windows\System32' directory.

**Comment by Phatastik** [comment]
Thanks Doc! That change to [Offline-Resources.psm1](https://raw.githubusercontent.com/DrEmpiricism/Optimize-Offline/8502bdaff0a104af4bbde13c272719b9092d5d1e/Src/Offline-Resources.psm1) did the trick!
