### ISSUE TITLE
[DOC] Unattend README misleading/incorrect

### ISSUE THREAD

**Issue by ImportTaste** [DrEmpiricism/Optimize-Offline#163]
>If adding additional user content, place an unattend.xml to be imported into the image here.
>
>This unattend.xml answer file acts indentically to an autounattend.xml answer file placed in the root of the installation media.

This isn't entirely true, any `windowsPE` or `offlineServicing` configuration pass (i.e. phases 1 & 2) must be contained within autounattend.xml, as the 'Panther' unattend.xml cannot apply those settings. This should be properly documented.

**Comment by DrEmpiricism** [comment]
OfflineServicing does not require an autounattend.xml and also why the module directly applies the unattend.xml directly to the offline image as well as copying it to the Panther directory.

**Comment by ImportTaste** [comment]
@DrEmpiricism What about `windowsPE`? Because the only reason I came to this conclusion is that only phases 3-7 were working when I used OO's method, only by applying it to the root system drive as autounattend.xml could I get phases 1 and 2 to work.
