### ISSUE TITLE
[BUG] DontUsePowerShellOnWinX in $RegistryData.DisableTracking

### ISSUE THREAD

**Issue by mchubby** [DrEmpiricism/Optimize-Offline#169]
**Describe the bug**
The DontUsePowerShellOnWinX registry tweak is classified in $RegistryData.DisableTracking

AFAICT it is not a privacy issue, and looks more like the author's preference setting it to 1

**Additional content or data**
Should be commented out and moved elsewhere (add your input below if you disagree)

**Comment by DrEmpiricism** [comment]
Then manually remove it from the registry function.

**Comment by DrEmpiricism** [comment]
You're free to comment out whatever registry settings you do not want applied.
