### ISSUE TITLE
Request: bypass registry optimisations

### ISSUE THREAD

**Issue by CarlosMerc** [DrEmpiricism/Optimize-Offline#17]
Hi,
I would like to use the script for everything other than the registry optimisations (although keeping getting rid of defaultuser0 and any other registry cleanups related to removing features/services). Something like a -NoRegistry switch? Leaving current registry switch out still produces all the altered registry changes (as noted by the log).

I prefer to use group policy scripts after the OS has installed.

**Comment by DrEmpiricism** [comment]
Hello, I have removed the automatic value of "Default" that automatically sets when the script is run, so now if you omit the -Registry parameter it will skip setting any of the registry optimizations.
