### ISSUE TITLE
[BUG] Windows Photo Viewer doesn't work, application doesn't open graphic files 

### ISSUE THREAD

**Issue by MajkelP** [DrEmpiricism/Optimize-Offline#172]
In version 4.0.0.10 after removing "Microsoft.Windows.Photos" app, - default Windows Photo Viewer doesn't work. I did not tried on previous builds. (4.0.0.9, 4.0.0.8, 4.0.0.7..)

![WindowsPhotoViewer](https://user-images.githubusercontent.com/52548659/80948214-f416ef80-8df1-11ea-978a-2890ca33176d.PNG)

After clicking on any jpg,bmp,tif file nothing is happens, PhotoViever seems to be installed but maybe there is an associations problem. 

- Image Name: Windows 10 Enterprise
- Image Build: 18363.815
- Host Environment: Windows 10 Enterprise 1909
- Parameters Passed: WindowsApps "whitelist" 

On WhiteList i left only:
"Microsoft.DesktopAppInstaller",
    "Microsoft.StorePurchaseApp",
    "Microsoft.VP9VideoExtensions",
    "Microsoft.WindowsStore",
    "Microsoft.XboxIdentityProvider"
I removed Microsoft.Windows.Photos to get default Windows Photo Viewer.  

In the log file: "RegistrySettings.log" there is information that: "Restoring Windows Photo Viewer."
Las time I used script version Optimize-Offline 3.2.7.7 and there I had this message and PhotoViewer did work. 

[Optimize-Offline.log](https://github.com/DrEmpiricism/Optimize-Offline/files/4573585/Optimize-Offline.log)
[PackageSummary.log](https://github.com/DrEmpiricism/Optimize-Offline/files/4573586/PackageSummary.log)
[RegistrySettings.log](https://github.com/DrEmpiricism/Optimize-Offline/files/4573587/RegistrySettings.log)
[OptimizeErrors.log](https://github.com/DrEmpiricism/Optimize-Offline/files/4573589/OptimizeErrors.log)

**Comment by DrEmpiricism** [comment]
I am able to right-click and select the 'Open With..." sub-context menu where it gives me the option of selecting the default Windows Photo Viewer. Do you not have that option?

**Comment by MajkelP** [comment]
Thank you for your answer. I have sub-context menu but when I selecting Windows Photo Viewer nothing happens. I tried the newest script version 4.0.1.0 and I still have the problem. Graphics files do not open. (jpg, bmp, png, tif). I can see preview of the files, I can set a desktop background. When I download and run this reg: https://www.tenforums.com/attachments/tutorials/198320d1533487488-restore-windows-photo-viewer-windows-10-a-restore_windows_photo_viewer_all_users.reg Photo Viewer starts work. 

![1](https://user-images.githubusercontent.com/52548659/83560777-0a11f000-a517-11ea-84e4-b0d48c18ac8e.PNG)
![2](https://user-images.githubusercontent.com/52548659/83560789-0e3e0d80-a517-11ea-93b3-1145d70b9e62.PNG)

**Comment by victor-bayas** [comment]
Can confirm that Photo Viewer doesn't works

**Comment by DrEmpiricism** [comment]
The registry code has been updated in the latest build which has fixed this issue.
