### ISSUE TITLE
[BUG] Crashing out immediately due to dism

### ISSUE THREAD

**Issue by gut5** [DrEmpiricism/Optimize-Offline#173]
**Describe the bug**

Optimize-Offline-4.0.0.10 crashes as soon as I start it with the following message

```
PS C:\winstuff\Optimize-Offline-4.0.0.10> .\Start-Optimize.ps1
Import-Module: The script 'Optimize-Offline.psm1' cannot be run because the following modules that are specified by the "#requires" statements of the script are missing: Dism.
```

**Screenshots**

**Please complete the following information:**

- Image Name: Windows 10 Education
- Image Build: 19041.208
- Host Environment: Win 10 LTSC
- Parameters Passed: default, nothing added to configuration.json except the image path

**Additional content or data**

Powershell 7.0 (running as admin)

I also ran the "Get-Module -Name Dism" command but it returns nothing.
Dism.exe is present and working normally though. So I don't know why it's complaining about Dism.

This line was changed in the configuration.json 
```
  "SourcePath": "C:\winstuff\19041.208_amd64_en-us_professional_96f61392_convert_virtual\UUPs",
```

I also tried the path at 

```
  "SourcePath": "C:\winstuff\19041.208_amd64_en-us_professional_96f61392_convert_virtual",
```

**Comment by strotee** [comment]
What does `"SourcePath": "C:\path\to\file.ISO",` get you?

**Comment by gut5** [comment]
@strotee  same error (dism module)

**Comment by DrEmpiricism** [comment]
PowerShell 7.0 does not automatically inherit the default modules (or overall file structure) PowerShell 5 does, and as such, the Dism cmdlets are not present in PowerShell 7 by default, hence why nothing is returned when you type the command `Get-Module -Name Dism` 

Run Optimize-Offline with PowerShell 5

**Comment by gut5** [comment]
Thanks for pointing that out in the readme
