### ISSUE TITLE
WARNING: Unsupported Image Version: [10.0.19041.264] [BUG]

### ISSUE THREAD

**Issue by truefriend-cz** [DrEmpiricism/Optimize-Offline#176]
Unsupported Windows Image Version: [10.0.19041.264]

After run script show: WARNING: Unsupported Image Version: [10.0.19041.264]

Tested image version build: Windows 10 2004 x64 ENG
Script version: 4.0.1.0

**Comment by DrEmpiricism** [comment]
The only way this would happen is if the actual build metadata is, for some reason, not being returned properly when Optimize-Offline ensures the image is fully supported.

I have had no problems in previous 19041 updated images but have not tried the latest 264 to see if anything has changed with its metadata. I will update a 19041 image right now to the latest and check, then update this if any issue arises.

I use my own PowerShell offline module to update images.

**Comment by DrEmpiricism** [comment]
I had no issue with version 10.0.19041.264 after integrating offline updates with my servicing module.

![Win10_19041](https://user-images.githubusercontent.com/20321974/83581096-daa9b600-a50b-11ea-84f8-3213727cda08.png)

**Comment by slickag** [comment]
Try using another PowerShell version. I kept getting the same error when I ran the script using PowerShell v7 (the newest one) but it ran fine using the powershell.

**Comment by DrEmpiricism** [comment]
I did update a Resource Function today to improve how image metadata was returned, as I encountered this error a few times with the newest 20H2 builds. See if the new version of Optimize-Offline fixes this issue.
