### ISSUE TITLE
Issue with the last 3.1.2.9 - 11/26/2018 version?

### ISSUE THREAD

**Issue by Ainatar** [DrEmpiricism/Optimize-Offline#18]
Hi, i was testing the lastest version (3.1.2.9 - 11/26/2018) with LTSC 2019, and im getting this error (with the 3.1.2.9 - 11/25/2018 version it didn't happen):

Applying the Microsoft Store Application Packages.
Applying the Microsoft Edge Browser Application Packages.
Applying Optimized Registry Settings.
Get-ItemProperty : No se encuentra la ruta de acceso 'HKLM:\WIM_HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Run' porque no existe.
En D:\Programas\W10CU\Optimize-Offline-master\Optimize-Offline.ps1: 2085 Carácter: 14
+ ...        If ((Get-ItemProperty -LiteralPath "HKLM:\WIM_HKCU\SOFTWARE\Mi ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (HKLM:\WIM_HKCU\...rentVersion\Run:String) [Get-ItemProperty], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetItemPropertyCommand

Generating a Setup Post-Installation Script.
Cleaning-up the Image.
Post-Optimization Image Health State: [Healthy]
Saving and Dismounting the Image.
Rebuilding and Exporting the Image.
Finalizing Optimizations.
ADVERTENCIA: Optimize-Offline completed in [12] minutes with [1] errors.

I think its an innocuous error, but i notify it anyway.

**Comment by Ainatar** [comment]
But the fix was not applied to the repository right? Because i downloaded it again, and still have the same issue.

**Comment by DrEmpiricism** [comment]
Show me the log files, please.

**Comment by Ainatar** [comment]
[OptimizeLogs.Zip](https://github.com/DrEmpiricism/Optimize-Offline/files/2616910/OptimizeLogs.Zip)

**Comment by DrEmpiricism** [comment]
I will set that to continue on error if that run property is not preset, as they can differ quite frequently from build-to-build.

Give me a few minutes to edit the script, run the debugger and update the repository file.
