### ISSUE TITLE
(question) how to delete Start menu items

### ISSUE THREAD

**Issue by strotee** [DrEmpiricism/Optimize-Offline#188]
I originally posted this on MDL but was advised to post it here. This is less of a bug and more of a technical how-to question.  

If I wanted to remove the icons from the Start menu ([see pic](https://i.imgur.com/tGi8DSC.png)), it appears I need to modify Optimize-Offline.psm1 around lines 1551 - 1564 ([see pic](https://i.imgur.com/bvaxlFQ.png)). Is that doable or will this break anything during its execution? I'm utilizing normal comments (<# code #>), I assume this is right. 

Edit: I ran it and it installed without issue, those items are not on the Start menu.

**Comment by DrEmpiricism** [comment]
You can just right-click them and select 'Unpin from Start'

No tile pinned to the Start Menu is permanent.
