### ISSUE TITLE
Error Logs With New Commit

### ISSUE THREAD

**Issue by KedarWolf** [DrEmpiricism/Optimize-Offline#19]
Error logs:
Cannot find path 'HKLM:\SOFTWARE\Microsoft\Windows Kits\Installed Roots' because it does not exist.
Cannot find path 'HKLM:\WIM_HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Run' because it does not exist.
I have ADK 1809 Deployment Tools installed.

**Comment by DrEmpiricism** [comment]
What architecture are you running this script on?

**Comment by KedarWolf** [comment]
LTSC 2019 ISO on an LTSC 2019 installed PC, updated to Insider updates.

**Comment by DrEmpiricism** [comment]
This was due to the lack of OneDrive properties in LTSC the script checked for that were benign to any actual processes.
