### ISSUE TITLE
[Question] How do you re-enable Sync & Login with Microsoft Edge

### ISSUE THREAD

**Issue by AnnoyYouWithIssue** [DrEmpiricism/Optimize-Offline#192]
I've been searching for hours and I can't figure out how to either revert it or prevent it from changing.

Greatly appreciate your help in solving this, and thank you for all the effort you two put in!

![image](https://user-images.githubusercontent.com/61725097/90619645-52f84d00-e1c6-11ea-8d0b-f28ad09fade4.png)
![image](https://user-images.githubusercontent.com/61725097/90619706-64d9f000-e1c6-11ea-99a7-4c51847099e3.png)

**Comment by DrEmpiricism** [comment]
Optimize-Offline does not disable Microsoft Edge synchronization, though that's not to say the removal of a System Application/Capability/Package would not affect it from working properly.

According to my ADMX templates, the Group Policy setting for this is located here:
Computer Configuration\Administrative Templates\Windows Components\Sync your settings

Lastly, is this for Edge HTML or Edge Chromium?

**Comment by AnnoyYouWithIssue** [comment]
Edge Chromium.

I was following the guide on MDL/GitHub that listed a bunch of services that could be safely removed and it seems to be a side effect of one of the ones listed. I tried to deduce it down to a specific service but wasn't able to after rebuilding and reformatting quite a few times.

I followed the rest of the guide exactly and only removed Edge/EdgeDevKit and Windows Defender (can't remember the name) and Sync worked perfectly with only those removed even with all of the registry tweaks enabled.

I only just realized that you're not the author of the thread on MDL as well, so sorry for wasting your time.

**Comment by DrEmpiricism** [comment]
Diving into this error a bit more, the exact error description is  "A specified logon session does not exist. It may already have been terminated." This kind of error is primarily isolated to domain-joined devices (usually a result of 'domain jumping').

Is your device connected to a domain by any chance?

I would recommend creating a new administrator profile and signing into it - keeping it in its default state - and then checking if synchronization works on a fresh, untouched account.

**Comment by AnnoyYouWithIssue** [comment]
Yes, when I format I always join a domain instead of logging into a Microsoft account.

Unfortunately I'm not in a situation at the moment where I can test and see if that would resolve the issue.

I appreciate all of your help!
