### ISSUE TITLE
[BUG] Set-Additional.ps1 causing Action Center not to load when clicked on

### ISSUE THREAD

**Issue by AnnoyYouWithIssue** [DrEmpiricism/Optimize-Offline#193]
**Describe the bug**
After a clean format, and while the Action Center is working, running Set-Additional.ps1 to activate additional changes removes the ability to use the Action Center. When you click on the Action Center after using that script, it attempts to load (as shown by a spinning blue circle), then stops as if it crashed.

**Screenshots**
![image](https://user-images.githubusercontent.com/61725097/91114843-d26a9e00-e656-11ea-814b-11c301787ae4.png)

**Please complete the following information:**

- Image Name: [Windows 10 Enterprise N.iso]
- Image Build: [19041.450]
- Host Environment: [Windows 10 Enterprise N]
- Parameters Passed: [-WindowsApps "Select" -SystemApps -Capabilities -Packages -MicrosoftEdge -Win32Calc -Registry]

**Additional content or data**
This bug? consistently happened with both the Set-Additional.ps1 file released on 8/23, and the previous version.

If I go into Notifications & Action Center and then click on the "Focus Assist" tab, the Settings window instantly crashes.

I've looked through the script a few times and can't find anything related to the Action Center, so I'm not sure if this is an intentional change or not.

**Log files**
Add any log files produced.

**Comment by verlain3** [comment]
AFAIK the responsible service for Notifications/Action Center is "WpnUserService" aka "Windows Push Notification Service". 

You need to enable it if you want those features
