### ISSUE TITLE
How can I choose multiple items in a gridview list?

### ISSUE THREAD

**Issue by xxTudorxx** [DrEmpiricism/Optimize-Offline#195]
When the gridview list appears,i can only choose one package/app/feature,then press OK.How can I choose multiple items in that list?
I know this is a really dumb question,but i couldn't find an answer anywhere and I can't figure it out.

**Comment by KedarWolf** [comment]
Hold the CTRL key and click each item. Or click the top item, hit SHIFT, click the bottom item, then they will all be selected, then hold the CTRL key and unselect the items you don't want from the list.

**Comment by xxTudorxx** [comment]
Thank you so much! I will go trough the de bloating process and finally get my lite iso.

**Comment by KedarWolf** [comment]
https://forums.mydigitallife.net/threads/optimize-offline-guide-windows-debloating-tool-windows-1803-1903-19h2-1909-20h1-and-ltsc-2019.80038/ A guide I made.
