### ISSUE TITLE
[BUG] Microsoft Store Paid Apps Not Installing After Running Set-Additional.cmd

### ISSUE THREAD

**Issue by KedarWolf** [DrEmpiricism/Optimize-Offline#201]
**Describe the bug**
Microsoft Store Paid Apps Not Installing After Running Set-Additional.cmd, Get an error Windows Update is disabled.
Paid apps work before running the script.
I checked and all Windows Update services and required services are running.

**Please complete the following information:**

- Image Name: Windows 10 Enterprise
- Image Build: 19042
- Host Environment: Windows 10 Enterprise
- Parameters Passed:
{
  "_Info": [
    "This is a JSON based Configuration file for Optimize-Offline.",
    "Ensure proper formatting is used when editing the JSON parameter values.",
    "Boolean parameter values use true and false. String parameter values must be enclosed in double-quotes."
  ],
  "SourcePath": "D:\\1\\Win10_19042.630_x64_2020-11-07.iso",
  "WindowsApps": "Select",
  "SystemApps": true,
  "Capabilities": true,
  "Packages": true,
  "Features": true,
  "DeveloperMode": true,
  "WindowsStore": false,
  "MicrosoftEdge": false,
  "Win32Calc": true,
  "Dedup": false,
  "DaRT": [
  ],
  "Registry": true,
  "Additional": {
    "Setup": true,
    "Wallpaper": false,
    "SystemLogo": false,
    "LockScreen": false,
    "RegistryTemplates": true,
    "LayoutModification": false,
    "Unattend": true,
    "Drivers": true,
    "NetFx3": true
  },
  "ISO": "No-Prompt"
}

**Comment by KedarWolf** [comment]
Fixed!!

It was XblAuthManager being one of the services disabled.

I enabled XblAuthManager, started it, and removed it from the Services.json. Now my paid store apps are installing.

**Comment by DrEmpiricism** [comment]
Good to know. I will add a note in the Set-Additional script with that info.
