### ISSUE TITLE
Getting Started?

### ISSUE THREAD

**Issue by ezuk** [DrEmpiricism/Optimize-Offline#21]
Would be cool to have a brief "Getting Started" writeup in the Readme, just explaining how to go about optimizing a system. I know it doesn't work on a live system -- so what would be the procedure, for someone who isn't an experienced Windows admin? :)

**Comment by DrEmpiricism** [comment]
The procedure for what?  All parameters and switches are explained, in detail, in the header of the script itself and there's even a Start.cmd that one can simply edit and then right-click - "Run as Administrator" to automatically call the script without having to manually input the parameters directly into the PShell console.

**Comment by ezuk** [comment]
So the questions I have are:

I am just a Windows user, on a live system (Win 10 Pro). I am able to get an ISO of course, and I understand that using the script would require me to re-install my system from scratch. Okay, that is my starting point.

So... Now what?

1. Obtain ISO
2. Run script
3. Put ISO on USB stick
4. Install?

Also, what happens with Windows Updates? Will a Windows Update revert these changes? Will these break future updates? Will I need to re-apply something to have this keep working?

Thank you!
