### ISSUE TITLE
"Disable Device Access for Universal Apps" is missing formally included value

### ISSUE THREAD

**Issue by Phatastik** [DrEmpiricism/Optimize-Offline#30]
The registry category "Disable Device Access for Universal Apps" used to include the value: {21157C1F-2651-4CC1-90CA-1F28B02263F6} which relates to letting apps read or send messages (text or MMS). 
Is this removed by design?

**Comment by DrEmpiricism** [comment]
These registry settings are no longer implemented; however, some were omitted from previous versions of the script because they caused issues during the OOBE and setup process.
