### ISSUE TITLE
ChangeLog opposite statement?

### ISSUE THREAD

**Issue by Phatastik** [DrEmpiricism/Optimize-Offline#33]
As written: Made multiple changes and removals to registry settings applied, as many of them have changed and are **not** applicable to older builds. As such, Optimize-Offline no longer supports builds lower than RS4 (17134).

I assume you meant... "**only** applicable to older builds"

**Comment by DrEmpiricism** [comment]
By "older builds" I meant older as in earlier builds, not older as in later builds.  I will make this clearer in today's update, thought.
