### ISSUE TITLE
Missing Sharing card

### ISSUE THREAD

**Issue by truefriend-cz** [DrEmpiricism/Optimize-Offline#34]
Hi Dev. You version v3.1.3.0 have problem. Missing tab for Drive/Folder Sharing card in Properties dialog. Do you can fix this?

**Comment by Phatastik** [comment]
Hi. The 'missing' Sharing tab in Properties dialog is a feature and not a problem. 
If you don't want this feature, remove the section titled "Disabling 'Share' from the Context Menu." 
You can change this 'online' by working with the effected registry key.
