### ISSUE TITLE
Missing all drivers

### ISSUE THREAD

**Issue by truefriend-cz** [DrEmpiricism/Optimize-Offline#39]
Dev. From version 3.1.3.2 after apply your script missing all based Drivers after install OS. (Grahics, Lan, Wan, etc.)
Manually add (from installed system) no allowed. Ended with error: E0000248

Tested on LTSC x64, command:
PowerShell.exe -NoProfile -ExecutionPolicy Bypass -File .\Optimize-Offline.ps1 -ImagePath "%SourcePath%" -MetroApps "Select" -SystemApps -Packages -Features -Win32Calc -Registry
From UI selected for removing only:
Microsoft.BioEnrollment
Microsoft.Windows.SecHealthUI
Microsoft.XboxGameCallableUI

**Comment by Ainatar** [comment]
Same problem here, with LTSC x64 too.

**Comment by DrEmpiricism** [comment]
This appears to have been caused by the registry setting that prevented automatic driver updates through Windows Update.  This setting has been removed in the new 3.1.3.4 script version.
