### ISSUE TITLE
Request: Grant-ProcessPrivilege GitHub page

### ISSUE THREAD

**Issue by Phatastik** [DrEmpiricism/Optimize-Offline#40]
I was wondering if you could share on GitHub the removed "Grant" region Helper Functions from Optimize-Offline 3.1.2.9. 
Grant-ProcessPrivilege; Function Grant-FileAccess; Grant-FolderAccess are extremely useful and powerful. 
A page with a brief explanation about them would help myself and others get the most benefit when applying them to our own scripts.

**Comment by DrEmpiricism** [comment]
Those were very "lite" versions of advanced functions I use in a security module I created a while back. But yes, I can re-upload them to a separate repository.

**Comment by Phatastik** [comment]
Is the advanced security module published on the PowerShell module site?
A published 'lite' version with a modicum of explanation could help people to shift away from using third party apps to perform these simple native functions.
