### ISSUE TITLE
1809 Build 17763 SmartScreen still functions

### ISSUE THREAD

**Issue by Phatastik** [DrEmpiricism/Optimize-Offline#42]
I did some online research before posting this 'issue' so I'm fairly confident that this is new to build 17763. My prior Optimize-Offline 17134 build works as expected.

In build 17763, 'SmartScreen' (C:\windows\system32\smartscreen.exe) occasionally runs when starting an application.
My image used Optimize-Offline to successfully disabled Windows Defender and I've confirmed that all the "Removing Windows Defender Remnants" registry settings are still correctly applied.

If it turns out that I'm alone with this issue, than, please let me know so I can try and figure out if I've done something stupid.
Else, if this is a known problem, do you have a suggested solution?

**Comment by DrEmpiricism** [comment]
Version LTSC or no?  If so, was Microsoft Edge or Windows Store integrated or not?

**Comment by Phatastik** [comment]
[17763] [Windows 10 Education] with Edge removed in the Gridview using SystemApps parameter.

**Comment by DrEmpiricism** [comment]
I will install them on virtual machines today and do some logging today to monitor inbound/outbound and see what the culprit is and tweak the script accordingly.

**Comment by DrEmpiricism** [comment]
Though later than anticipated, I do have an update on this.  In builds RS5+ (17763+) smartscreen.exe will silently connect to the internet using both inbound and outbound traffic.

I have been working on an optional 'New-UserSetup' automated script that can be optionally run on a live system to do some further automatic optimizations.  I will include a fix for this when I release that script.  You could also just add it new firewall rules for it:

- New-NetFirewallRule -DisplayName "SmartScreen Inbound" -Action Block -Description "Prevent SmartScreen Inbound Traffic." -Direction Inbound -Name "SmartScreen" -Profile Any -Program "%SystemDrive%\Windows\System32\smartscreen.exe" -ErrorAction SilentlyContinue | Out-Null

- New-NetFirewallRule -DisplayName "SmartScreen Outbound" -Action Block -Description "Prevent SmartScreen Outbound Traffic." -Direction Outbound -Name "SmartScreen" -Profile Any -Program "%SystemDrive%\Windows\System32\smartscreen.exe" -ErrorAction SilentlyContinue | Out-Null

**Comment by Phatastik** [comment]
belated thanks!
