### ISSUE TITLE
Question: DeDup

### ISSUE THREAD

**Issue by truefriend-cz** [DrEmpiricism/Optimize-Offline#43]
How (where) setting DeDup on LTSC windows?

**Comment by DrEmpiricism** [comment]
Per the ReadMe on the main page:

> With Optimize-Offline, the Data Deduplication packages and features available for Windows Server 2016 editions can be integrated into the offline image and enabled for use. PowerShell must be used to enable and manage Data Deduplication using its storage cmdlets. This information is readily available from the [Microsoft Document](https://docs.microsoft.com/en-us/powershell/module/deduplication/?view=win10-ps)
