### ISSUE TITLE
¿Error? with 3.1.3.5

### ISSUE THREAD

**Issue by Ainatar** [DrEmpiricism/Optimize-Offline#44]
Hi, editing an LTSC 1809 x64 iso all went well but ends with this (Error log is empty):

Applying Optimized Registry Settings.
Cleaning-up the Start Menu Layout Tiles.
Post-Optimization Image Health State: [Healthy]
Saving and Dismounting the Image.
Rebuilding and Exporting the Image.
Finalizing Optimizations.
ADVERTENCIA: Optimize-Offline completed in [22] minutes with [2] errors.
Remove-Variable : No puede quitarse la variable _ porque se optimizó y no es extraíble. Intente usar el cmdlet
Remove-Variable (sin ningún alias) o use el operador punto con el comando que utiliza para quitar la variable.
En D:\Programas\W10CU\Optimize-Offline-master\Optimize-Offline.ps1: 2525 Carácter: 118
+ ... t $DefaultVariables).InputObject).ForEach{ Remove-Variable -Name $_ }
+                                                ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (_:String) [Remove-Variable], SessionStateUnauthorizedAccessException
    + FullyQualifiedErrorId : VariableNotRemovableRare,Microsoft.PowerShell.Commands.RemoveVariableCommand

Remove-Variable : No puede quitarse la variable PSItem porque se optimizó y no es extraíble. Intente usar el cmdlet
Remove-Variable (sin ningún alias) o use el operador punto con el comando que utiliza para quitar la variable.
En D:\Programas\W10CU\Optimize-Offline-master\Optimize-Offline.ps1: 2525 Carácter: 118
+ ... t $DefaultVariables).InputObject).ForEach{ Remove-Variable -Name $_ }
+                                                ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (PSItem:String) [Remove-Variable], SessionStateUnauthorizedAccessException
    + FullyQualifiedErrorId : VariableNotRemovableRare,Microsoft.PowerShell.Commands.RemoveVariableCommand

Any ideas? Thanks.

**Comment by DrEmpiricism** [comment]
These are errors pertaining to the removal of the variables set by the script which is removed in the update (which will be uploaded today) and are non-critical (i.e. irrelevant).  As stated, today's update resolves this issue.
