### ISSUE TITLE
Breaks 3rd party firewalls?

### ISSUE THREAD

**Issue by TheMCNerd2017** [DrEmpiricism/Optimize-Offline#45]
Not sure if it's intended, but 3rd party firewalls like TinyWall do not work correctly on Windows Installations modified with this script. I am not sure where exactly to post this, so I thought that I would post this here.

**Comment by DrEmpiricism** [comment]
I have not found any issues with 3rd party firewall utilities used in conjunction with an image optimized with this script such as Windows Firewall Control; however, I have tried TinyWall.  Moreover, this script does not change any of the default Windows Defender Firewall control settings and only adds necessary firewall rules via the offline registry hives for the disabling of Cortana telemetry and Data Deduplication integration.  Even the removal of the Windows Defender system application provisioning does not affect the actual Windows Defender Firewall, though I will test TinyWall on a Virtual Machine with debugging and logging from my network server and see if there any any conflicts.  Perhaps it's taking issue with the updated Hosts file?

**Comment by DrEmpiricism** [comment]
I have 3 VMs running with 17134 and 17763 and the default Windows Firewall presents no issues.  I am not concerned about 3rd party tools.
