### ISSUE TITLE
Microsoft Store Not Working On LTSC 2019

### ISSUE THREAD

**Issue by KedarWolf** [DrEmpiricism/Optimize-Offline#48]
No error message, just won't open. I used the  -WindowsStore parameter.

**Comment by KedarWolf** [comment]
When I add the Store using the tools found on MyDigitalLife "[GUIDE] Add Store to Windows 10 EnterpriseS SKU (LTSB/LTSC)" the Store works.
https://forums.mydigitallife.net/threads/guide-add-store-to-windows-10-enterprises-sku-ltsb-ltsc.70741/page-30#post-1468779

**Comment by DrEmpiricism** [comment]
I have no problems with Windows Store:

[Imgur](https://i.imgur.com/MSRteVL.png)

**Comment by KedarWolf** [comment]
It must be one of the Regedit files I use. Working on a clean install with no tweaks.
