### ISSUE TITLE
Iso With 

### ISSUE THREAD

**Issue by KedarWolf** [DrEmpiricism/Optimize-Offline#50]
Issue With 'Hide Extensions For File Types' Not Disabled.

If you don't disable this option in File Explorer then the extraction of the Windows ISO fails on start-up of the script.

If you could enable it by default with the script it would be helpful

**Comment by DrEmpiricism** [comment]
By default that is disabled, and considering the script itself does not change this in the image it's optimizing, I am not going to take the time to specifically accommodate a workaround on a live system simply because you have changed its default value.
