### ISSUE TITLE
Generate ISO failure

### ISSUE THREAD

**Issue by jimserio** [DrEmpiricism/Optimize-Offline#51]
Great tool! I spent a few hours scratching my head as to why the ISO image was not being created. There were no errors so it appears it was skipping that step.

The following line seems to grab both instances/paths for Windows Kits:

$ADK_ROOT = @("HKLM:\Software\Wow6432Node\Microsoft\Windows Kits\Installed Roots", "HKLM:\Software\Microsoft\Windows Kits\Installed Roots") | ForEach {

Because of this, the following test fails:

If (Test-Path -Path "$($OSCDIMG)\oscdimg.exe")

Because OSCDIMG contains both paths. My fix was to just delete the second HKLM key and it worked as expected. 

This was on Windows 10 v1803.

**Comment by DrEmpiricism** [comment]
Yeah originally it was set to test both paths but for whatever reason I changed it to only test if the variable does not return a $null value.

I will fix this.  Thanks for letting me know.
