### ISSUE TITLE
Proposal to add a feature - Updates

### ISSUE THREAD

**Issue by truefriend-cz** [DrEmpiricism/Optimize-Offline#52]
Hi dev. Do you plannig add function for adding to package MSU Updates?

**Comment by DrEmpiricism** [comment]
What do you mean "function for adding to package MSU Updates"?

**Comment by truefriend-cz** [comment]
Function for add to install.wim updates from MSU packages. (KB*.msu packages).
Sorry. My social english is little/bad.

**Comment by DrEmpiricism** [comment]
Oh you mean update integration (i.e. Servicing Stack, Cumulative, etc.)?

**Comment by truefriend-cz** [comment]
Yes

**Comment by DrEmpiricism** [comment]
I already have a PowerShell script that does that, though if I were to incorporate that feature into Optimize-Offline, it would be a separate function module/script that could get called from the main script.  Merging the two into one script would not be ideal.

**Comment by truefriend-cz** [comment]
Now I'm working on something similar but on BATch.
It should not be complicated. You only need to extract a folder with inverse sorting file allocation and apply.

My basic test script (without inverse sorting files):

```
for %%f in (Download\Updates\*.msu) do (
	echo installing update: %%f ...wait...
	wusa.exe %%f /quiet /norestart
	echo ok
)
```
Reverse sorting it's important to install only the latest update from the folder and skip the other updates.
Yes, better solution is check every MSU file a get version from MSU file :)

**Comment by DrEmpiricism** [comment]
I did not say it was complicated; I said it would not be ideal.  The ideal way to do it would be to have it as a separate module/script that can then be called into the main script thus creating two caller scopes, which is much easier to manage.

Lastly, the script you posted used SCCM for update integration (which I also do), and SCCM by default has error-checking, logging, automatic package updating, etc.
