### ISSUE TITLE
$IsLTSC and $WindowsStore always false

### ISSUE THREAD

**Issue by znevna** [DrEmpiricism/Optimize-Offline#56]
After scratching my head for a while not knowing what changed since few versions ago because windows store wasn't getting integrated in LTSC i decided to dig into the code and found this
https://github.com/DrEmpiricism/Optimize-Offline/blob/a68830eb7f9d51a985feed41a03ba6a62ba418cf/Optimize-Offline.ps1#L508
Which is always false since the image name is "Windows 10 Enterprise LTSC 2019" and it doesn't end in LTSC but in 2019. So an easy fix would be
` If ($WimInfo.Name -like "*LTSC*") `
Thanks.

**Comment by DrEmpiricism** [comment]
I have addressed this before:  PowerShell returns the Display Name as the Image Name when querying the LTSC XML metadata but omits '2019' from it, hence why there is no ending asterisk.

**Comment by znevna** [comment]
Hmm. Well, can I get back to you on this one? I've tested on a laptop that runs LTSB and I had the issue I've described, but I didn't check the output on those commands.
Indeed, here on LTSC it works as you said.
I'll check tomorrow at work and report back.

**Comment by DrEmpiricism** [comment]
You can certainly get back to me.  If you continue to have problems, you will have to detail things further: i.e. any returned errors, logs, etc.

**Comment by znevna** [comment]
Ok, seems like LTSB is to blame since this is the output of Get-WindowsImage on LTSB.
[Full Info](https://i.imgur.com/JVCCFuG.png)
Someone wishing to prepare an image to upgrade from LTSB to LTSC might encounter this issue.
Can be closed I think. I'll use it with my extra *.

**Comment by DrEmpiricism** [comment]
LTSB is not a supported build (1607) - this is explicitly stated numerous places and there's a reason for that. There are a lot of differences between LTSB and LTSC outside of simple aesthetics. Likewise, the changes between 1607 and 1709+ are hugely substantial, particularly at the kernel level.

**Comment by znevna** [comment]
I wasn't trying to use the script with a LTSB .wim, it was just running under LTSB, I've explained the scenario, but you didn't look at the printscreen I posted.
Cheers.
