### ISSUE TITLE
When Selecting Index Both Remain In Finished ISO.

### ISSUE THREAD

**Issue by KedarWolf** [DrEmpiricism/Optimize-Offline#57]
I believe it used to be is you select an Index only that Index remained in the ISO. 
Now after selecting an Index both remain when you go to install Windows.

This on LTSC 2019 with updates integrated beforehand with W10UI script.

**Comment by DrEmpiricism** [comment]
This was fixed in the most recent update to 3.2.4.1 and was because of the change to legacy DISM from PowerShell's cmdlet due to the latter being significantly slower and requiring more resources.
