### ISSUE TITLE
Question: About Additional .cmd Scripts

### ISSUE THREAD

**Issue by KedarWolf** [DrEmpiricism/Optimize-Offline#58]
Are .cmd scripts that are placed in the Additional\Setup folder that are tested and successfully disable services, add registry entries etc. applied to the image by Optimize-Offline when I run it?

And can I add a .ps1 script or even a .reg file to the Setup folder?

**Comment by DrEmpiricism** [comment]
No.  Optimize-Offline only copies them to Microsoft's recommended deployment directory.  It adds no script to the registry to be automatically executed.  That said, if Windows setup detects default startup scripts like SetupComplete.cmd, OOBE.cmd, ErrorHandler.cmd, etc. they WILL run during setup.

You can add any content you wish to the \Additional\Setup folder as it's designed for those users who want to add startup scripts (like I listed above - that automatically run during setup) to call other scripts or create specific system content during the setup of the OS.
