### ISSUE TITLE
Telemetry Level 0 (Security) should be also applied to the Education edition, not only to LTSC & Enterprise

### ISSUE THREAD

**Issue by Hyperyia** [DrEmpiricism/Optimize-Offline#63]
According to Microsoft's documentation, the Telemetry Level "0" is also supported on the Education SKU, not sure about some others like "Pro Education" or "Pro for Workstations", but the script applies it only to LTSC & Enterprise SKUs, should apply it also to the Education at least.

**Comment by DrEmpiricism** [comment]
Yes telemetry level '0' is applicable for Education editions, too. I will add that to the next update.
