### ISSUE TITLE
UWP File Explorer Taskbar Problem.

### ISSUE THREAD

**Issue by KedarWolf** [DrEmpiricism/Optimize-Offline#67]
UWP File Explorer won't stay unpinned from the taskbar.

I tried:

```
DEL /F /S /Q /A "%AppData%\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar\*"
REG DELETE HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Taskband /F
taskkill /f /im explorer.exe
start explorer.exe
```
but it always returns.

**Comment by DrEmpiricism** [comment]
That's because it's set to replace as a task bar item.  I am adding a new layout today to the script that does not do that.

**Comment by DrEmpiricism** [comment]
This is corrected in today's build.  Closing.
