### ISSUE TITLE
Found a few errors and mistakes in the registry section

### ISSUE THREAD

**Issue by Hyperyia** [DrEmpiricism/Optimize-Offline#68]
In the "Disabling Cortana and Search Bar Web Connectivity." sub-section:

`    Set-ItemProperty -LiteralPath "HKLM:\WIM_HKCU\SOFTWARE\Microsoft\InputPersonalization" -Name "RestrictImplicitTextCollection" -Value 0 -Type DWord -ErrorAction SilentlyContinue
    Set-ItemProperty -LiteralPath "HKLM:\WIM_HKCU\SOFTWARE\Microsoft\InputPersonalization" -Name "RestrictImplicitInkCollection" -Value 0 -Type DWord -ErrorAction SilentlyContinue`

Both should be set to "1" to Disable, as the "0" DWord value Enables them.

Also, the tweak:

`    Set-ItemProperty -LiteralPath "HKLM:\WIM_HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced" -Name "TaskbarSmallIcons" -Value 1 -Type DWord -ErrorAction SilentlyContinue
`

is doubled in two places: "Disabling Explorer Document and History Tracking." and "Enabling Small TaskBar Icons." - should be removed from the first one IMO.

**Comment by DrEmpiricism** [comment]
Thanks. These have been corrected.
