### ISSUE TITLE
New Error

### ISSUE THREAD

**Issue by avogarden** [DrEmpiricism/Optimize-Offline#69]
C:\Optimize-Offline.ps1 : A parameter cannot be found that matches parameter name 'ImagePath'.
At line:1 char:24
+ .\Optimize-Offline.ps1 -ImagePath "C:\install.wim" -MetroApps "All" - ...
+                        ~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Optimize-Offline.ps1], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Optimize-Offline.ps1

**Comment by DrEmpiricism** [comment]
Always read the ChangeLog.md for new builds:

> The -ImagePath parameter has been renamed to -SourcePath.

**Comment by avogarden** [comment]
Thanks for quick reply. Appreciate your time and effort. Checking for update for new image build 18362.53.
