### ISSUE TITLE
Solid Compression Problem Still There

### ISSUE THREAD

**Issue by KedarWolf** [DrEmpiricism/Optimize-Offline#73]
Using the script on a Windows LTSC 2019 ISO the Optimize Offline created ISO still has both an install.wim and install.esd and is 6.45GB in size.

Any way the script can delete the install.wim before creating the ISO?

It will just stop me needing to extract the ISO, delete the install.wim, then creating a new ISO with the Windows Kit and oscdimg.exe.

On a side note using Solid Compression takes me about 17 minutes with an overclocked 9900k PC.

**Comment by DrEmpiricism** [comment]
Please stop making threads repeatedly.

**Comment by KedarWolf** [comment]
Sorry, it was closed before with no comment, explanation or resolution.
