### ISSUE TITLE
How to make Optimize-Offline use my own folder with DISM instead of it always using the Host OS DISM?

### ISSUE THREAD

**Issue by Hyperyia** [DrEmpiricism/Optimize-Offline#74]
Hi, the script didn't detect Oscdimg tool despite having ADK installed on my host OS, so i copied the "Oscdimg" folder from 1903's ADK to the Optimize-Offline's script "Resources" folder & i've edited .ps1 file to point to it - it has worked fine.
However, can i do the same thing with DISM? I want to use my own 1903's ADK DISM folder to make Optimize-Offline fully "standalone" without it depending on the host OS, however i don't really know what to edit in the .ps1 file in the case of DISM.

**Comment by DrEmpiricism** [comment]
DISM command-line is only used in two places in the script where PowerShell offers no cmdlets for the process it runs: one is to import app associations and the second is to compress the .wim to .esd using solid compression.  Moreover, to make any script completely 'standalone,' you need to use the system's native API and dll files only.  My own personal imaging module is completely standalone and uses only native API and dll files (Wimgapi, advapi32, virtdisk, etc.) so it can be used in PE environments, too, and requires no installations of any additional kits or the like.

Also, Optimize-Offline uses the DISM cmdlets via the default Dism module package.  To use DISM command-line (to utilize your own DISM executable), you would also have to convert the commands to work with the DISM executable. Likewise, many commands that use the pipeline to attain information to process optimizations would no longer work.

As far as the Oscdimg tool is concerned, the next update will have an additional way to create a bootable ISO if it cannot retrieve the ADK paths. That said, these ADK paths it retrieves are the ADK paths Microsoft specifically uses for processes like creating DaRT ISO files, etc. and are there specifically for other tools and scripts to attain the ADK's root path.
