### ISSUE TITLE
No Windows Subsystem For Linux Option Available To Enable.

### ISSUE THREAD

**Issue by KedarWolf** [DrEmpiricism/Optimize-Offline#75]
I've always enabled the Windows Subsystem For Linux with the script but now the option is not available. I checked on a clean install of Windows and it's still not enabled by default.

Can it be added?

**Comment by KedarWolf** [comment]
Sorry, I forgot to mention this is with a 18362 ISO.

**Comment by DrEmpiricism** [comment]
I have never enabled this feature but will later today and see what the deal is.

What version of Windows are you trying to enable it for (Enterprise, Pro, Pro for Workstations, etc.)?

**Comment by KedarWolf** [comment]
18362.145 (updates integrated)  Enterprise.

On LTSC 2019 you could enable the Linux Subsystem with the script.

**Comment by KedarWolf** [comment]
But I haven't checked LTSC 2019 with the latest version on the script.

**Comment by KedarWolf** [comment]
Sorry, I'm being unclear, it was an option in LTSC 2019 in the Enable Features options.

I'm going to check with the latest script in LTSC 2019 when I get home from when in 8 hours or so.

**Comment by DrEmpiricism** [comment]
It shows up and enables fine on LTSC 2019:

![Enable_Features](https://user-images.githubusercontent.com/20321974/58835289-926b6580-8623-11e9-88ee-4f5b51d4bdf9.png)
![Enable_Features2](https://user-images.githubusercontent.com/20321974/58835291-926b6580-8623-11e9-9c13-df5fa97e015d.png)

**Comment by KedarWolf** [comment]
Yes, but it doesn't show 18362 Enterprise.

**Comment by DrEmpiricism** [comment]
Shows up fine for me.

![Linux_Subsystem](https://user-images.githubusercontent.com/20321974/58838487-cb5c0800-862c-11e9-9ba0-ee59e7919dd5.png)

**Comment by DrEmpiricism** [comment]
Also shows up on the executable version of Optimize-Offline:

![Linux_Subsystem](https://user-images.githubusercontent.com/20321974/58838876-f7c45400-862d-11e9-9785-bfe6cf41af73.png)

**Comment by KedarWolf** [comment]
It might be because I made my Windows 10 Enterprise 18362.1 ISO with the UUP dump website.

I will check later with the official MVS 18362.30 ISO with latest updates W10UI integrated into it, should be the fix.

**Comment by KedarWolf** [comment]
Oh, and where can I get the executable version of the script? I'd like to check it out.

Has it been released?

Lastly, to smaller developers, I donate small amounts of money to support them. Do you have a donations link or anything if it's okay?

**Comment by DrEmpiricism** [comment]
The executable has not been publicly released yet. It has been in use by a handful of people for a few months now and will be released publicly here once I am confident its capabilities across all builds it supports. Moreover, it's not a script but a full Windows Form project that utilizes Microsoft's imaging APIs/DLLs (Wimgapi, Virtdisk, DISM, etc.) as well as my own DLLs.

A few of the things it does:

-Full ISO re-imaging
-Full WIM/ESD/UUP/etc. compression to and from other image-types.
-Complete conversions of an OS (similar to my Pro for Workstations conversion executable on GitHub).
-Image capturing
-Image expanding (applying)
-Proper answer file creation that utilizes an actual XML writer and not just a string with variables that can be edited.
-BIOS access/backup/editing from within Windows (determines specific vendors' dedicated namespace and accesses it).
-Full optimization functions of an offline image - this includes PROPER component package removal, where the permanency values are changed before the package is removed, and the DISM.API is used to allocate all package structures and then removed properly. None of this junk with making them visible in the registry, force removing them, and then haphazardly removing registry keys, etc.
-Full WinPE creation/building
-Multiple add-on implementations, with custom packages extracted and modified from more advanced builds. As an example, one can apply a full ADMX Group Policy package with all optimized and secure policy templates that ensures the Group Policy settings reflect the changes from within the registry itself.
-Full control over more advanced Windows features with multiple wrappers to utilize them easily. For example, retrieving Secedit.inf security policy files and returning an editor for them, affording complete control over one's security policy and User Rights and security policies across a network.
-Interop namespace control for complete control over even hardware peripherals on a device that are generally only accessible to vendors, OEMs and the like.
-Device LSA namespace session authenticating, for control over the device firmware from within Windows and without having to actually boot into the firmware.
-Conversions to MBR, UEFI, ReFS, etc.
-Abilities to split and merge full RAID arrays, whether physical or virtual.
-Full BitLocker control beyond what Microsoft offers.
-Numerous crypto-creators utilizing multiple cryptographic CSP/APIs available that the device will use for hardware security device provisioning (i.e. PKI key creation, TPM password generation, etc.) and additional password generators using Security.Cryptography.CryptoStream, Security.Cryptography.PasswordDeriveBytes and Intersecting Vector Cryptology Hash and Salting.
-Full .CVS exporting (with proper formatting) of various security attributes.
-Many network (private/public/small) features for resolving users across networks to verify account validity,
-Full network or independent deployment options, again, utilizing multiple server-grade features implemented into client SKUs (MDT, SCCM, etc.) Examples include the ability to sent boot-codes across PCs or a network, or to your own device from a WinPE build, to immediately remedy boot issues (also allows for full UEFI Windows 7 installations WITHOUT CSM).
-Complete custom cmdlets for accessing and editing the registry using the .NET Framework class to access a specific namespace that the registry interacts with, which allows for complete registry control.

**Comment by KedarWolf** [comment]
Never mind, it's there, just in a different location in the Enable Features list and I missed it.
