### ISSUE TITLE
Set-Privacy script error

### ISSUE THREAD

**Issue by verlain3** [DrEmpiricism/Optimize-Offline#76]
I tried running this new script on two machines and both gave me this error:

![Untitled](https://user-images.githubusercontent.com/15094643/58899551-1fcaba80-86f5-11e9-8ad8-9bbf2c056ec0.png)

Script runs > shows applying settings > gives error > closes and deletes Set-Privacy.bat & Set-Privacy.ps1 files

I'd also like to ask if by disabling the Scheduler Tasks present in this script we might "cripple" the Event Viewer logs? I use it to monitor WHEA errors while testing my Overclocks and i've noticed "QueueReporting" which is tied to Windows Error Reporting and i'm not sure if this is related to Event Viewer to function properly

**Comment by DrEmpiricism** [comment]
That's a typical error when the Dnscache is already in a stopped state and can be ignored. The files auto-delete to prevent multiple users from running the script on the same device and is designed to be used by the original administrator who installs the OS. You can, however, prevent this from just removing the two lines in the batch file:

DEL /F /Q "%~dp0Set-Privacy.ps1" >NUL 2>&1
DEL /F /Q "%~f0" >NUL 2>&1

**Comment by verlain3** [comment]
The DNS Client is showing as running under Services though, isn't this what you meant by "in a stopped state"?

![Untitled](https://user-images.githubusercontent.com/15094643/58907192-86f06b00-8705-11e9-8859-4499f259f5e2.png)

**Comment by DrEmpiricism** [comment]
The DNS Cache is only stopped temporarily for certain tasks. The script does not force the cache to stop in case of any dependency services being used, so if there are dependency services in use by the DNS Cache, or there is an Answer/Receive on a Record Entry within the DNS Cache, it will not stop unless forced to do so and the DNS Cache should only be forced if update components are being reset or the network itself is being restarted. That said, the scripts have been updated and now details of the results are ouput to a text file of the same name.

**Comment by verlain3** [comment]
Thanks for the explanation @DrEmpiricism 

As for the Event Viewer thing, guess i will have to test and see if disabling certain tasks/services in the script prevent some logs from being registered

**Comment by DrEmpiricism** [comment]
The tasks in the script by default are all tasks that are safe to disable in respect that no core components are affected.  Some software and tools may require certain services or tasks to be enabled in order to assign a dependency service to it.  Some backup software works this way, as does many logging functions and programs.

You can get details about all tasks or services using the Get-ScheduledTask and Get-Service cmdlets.  On my personal workstation PC I have all the tasks and services in that file disabled and many more. Compared to some scripts, the tasks and services Set-Privacy disables is very 'lite'.

**Comment by verlain3** [comment]
In one of my machines after using other methods similar to this script, Event Viewer only reports certain entries - WHEA errors are not reported anymore and i could never find why. If i use FullEventLogView application from NirSoft and filter WHEA i can see those, which is odd.

> Compared to some scripts, the tasks and services Set-Privacy disables is very 'lite' 

I agree, looking at the .ps1 it's simple and easy to edit. Like i said, i will need to start fresh (format c:) apply this script and see if the problems persists or everything works as intended afterwards.

Feel free to close this, ty!
