### ISSUE TITLE
-Drivers Switch Error, Latest Build.

### ISSUE THREAD

**Issue by KedarWolf** [DrEmpiricism/Optimize-Offline#77]
Deleted, -Additional switch needed, not -Drivers.

**Comment by KedarWolf** [comment]
But should remove the -Drivers switch in the example in the ReadMe.

**Comment by DrEmpiricism** [comment]
Per the ReadMe located in the Drivers directory:

> Any driver .inf file(s) or full driver package folders added herein will be integrated into the image when the -Additional switch is used.
