### ISSUE TITLE
Script On install.wim Issue

### ISSUE THREAD

**Issue by KedarWolf** [DrEmpiricism/Optimize-Offline#79]
Someone in MyDigitalLife tried to use the latest script on just an install.wim, not an ISO, and posted.

"But the script never manages to save the wim successfully:

I didn't provide the iso but the install.wim, maybe that's why it goes wrong after it saved the install.wim in the temp folder and deletes it to save the zipped reports/logs in that folder."

```
Dismount-WindowsImage : The system cannot find the file specified.

At C:\Optimize-Offline-master\Optimize-Offline.ps1:198 char:12
+     [void](Dismount-WindowsImage -Path $MountFolder -Discard -Scratch ...
+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Dismount-WindowsImage], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.DismountWindowsImageCommand
Get-Process : Cannot find a process with the name "Dism". Verify the process name and call the cmdlet again.
At C:\Optimize-Offline-master\Optimize-Offline.ps1:196 char:5
+     Get-Process -Name Dism -ErrorAction SilentlyContinue | Stop-Proce ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Dism:String) [Get-Process], ProcessCommandException
    + FullyQualifiedErrorId : NoProcessFoundForGivenName,Microsoft.PowerShell.Commands.GetProcessCommand
Export-WindowsImage : Unable to load DLL 'unattend.dll': The specified module could not be found. (Exception from
HRESULT: 0x8007007E)
At C:\Optimize-Offline-master\Optimize-Offline.ps1:2312 char:16
+         [void](Export-WindowsImage @ExportInstall)
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Export-WindowsImage], DllNotFoundException
    + FullyQualifiedErrorId : System.DllNotFoundException,Microsoft.Dism.Commands.ExportWindowsImageCommand
```

I tested it myself and it said the script finished successfully but when I checked the install.wim I ran it on, no changes were committed to it, all the default packages and everything I removed were still there.

BTW, I'm not trying to find faults with your script, I love it! Just think you should know if there are issues. 

Sometimes I feel like I'm just picking fault with it and that's not my intention. :(

**Comment by DrEmpiricism** [comment]
There is an error in the path where the .wim file is suppose to be saved to so it never successfully gets saved once it's been exported.  I will fix that now in the file.
