### ISSUE TITLE
Suggestion: option to remove and/or disable Adobe Flash Player

### ISSUE THREAD

**Issue by ghysler** [DrEmpiricism/Optimize-Offline#8]
Title says it all. I can't understand Microsoft's decision to include this software in LTSC (N) as well. Even more so because Adobe is planning EOL on Flash by the end of 2020: https://theblog.adobe.com/adobe-flash-update/

If you could build in an option in your script for removing and/or disabling Adobe Flash Player, that would be awesome.

**Comment by DrEmpiricism** [comment]
I will look into this a bit further today on a VM and modify the script accordingly.
