### ISSUE TITLE
Getting warning and then it exits: WARNING: "Windows.iso" does not contain valid Windows Installation media.

### ISSUE THREAD

**Issue by HarjitSi** [DrEmpiricism/Optimize-Offline#81]
Went to: https://www.microsoft.com/en-us/software-download/windows10 and used the "Download tool now" to create a windows.iso file.

Modified start.cmd to point to the location of windows.iso and ran startup.cmd in an elevated command prompt.

Got the warning shown in the title:
WARNING: "Windows.iso" does not contain valid Windows Installation media.

Mounted windows.iso and searched for install.wim and there isn't such a file, thus the error.

Help and thanks!

**Comment by DrEmpiricism** [comment]
This is not a problem with the script and does not belong here.
