### ISSUE TITLE
(ISSUE FOUND) Start-Process : Cannot convert 'System.Object[]

### ISSUE THREAD

**Issue by Aidolii** [DrEmpiricism/Optimize-Offline#85]
This is a continuation of #80 which was continued when the OP posted an unrelated issue toward the bottom and I guess @DrEmpiricism assumed it was why the problem was happening.

I've narrowed down the issue.

![image](https://user-images.githubusercontent.com/37132025/59225081-73298680-8b95-11e9-98dd-88a7c0a28708.png)

This happens when you have both the x64 and x86 entries in your registry and this is a legitimate bug. (Vindication is always such a relief.)

**Comment by DrEmpiricism** [comment]
This is not a legitimate bug and you and was corrected because you continue to post 'issues' from older versions of the script instead of using the latest ones.

**Comment by Aidolii** [comment]
@DrEmpiricism The commit was titled 'Minor process optimizations' and the last issue made it sound like you didn't think there was a bug. Sorry for not realizing it was fixed. :\

**Comment by Aidolii** [comment]
Why?
