### ISSUE TITLE
[FEATURE] INI File

### ISSUE THREAD

**Issue by 1Some1one1** [DrEmpiricism/Optimize-Offline#87]
I'm attempting to troubleshoot a problem I am having with the selections I've made on my Windows 10 Enterprise ISO. As with all troubleshooting, it is tedious. It would help a lot if I could simply edit an ini file for the MetroApps, Packages, and Features.

I notice that `-MetroApps` is followed by `"Select"`, so it is possible that, for that at least, it's already possible, but it would be difficult to figure out the syntax. Regardless, `-Packages` and `-Features` don't seem to have the same option.

Thank you for your time, I appreciate this script an awful lot.

**Comment by marcosviniciusf17** [comment]
Because each version of Windows has differences, it may be possible at the first startup to generate an XML file with all modifications. So in the next few uses simplify the process.

**Comment by DrEmpiricism** [comment]
I am looking into implementing a config file in an upcoming version.
