### ISSUE TITLE
Does Optimize Offline Apply Drivers To boot.wim?

### ISSUE THREAD

**Issue by KedarWolf** [DrEmpiricism/Optimize-Offline#89]
If it doesn't, could it be enabled? 

Would be good for drivers to be added to boot.wim and install.wim in some cases.

**Comment by DrEmpiricism** [comment]
It does not apply drivers to the boot.wim but it's something that could be incorporated.

**Comment by KedarWolf** [comment]
That would be great!! I always add my drivers to my boot.wim for setup as my Ethernet not detected by default and I've had issues with RAID and M.2s etc.

**Comment by DrEmpiricism** [comment]
I will add that to the next script release.

**Comment by KedarWolf** [comment]
Thank you.

**Comment by DrEmpiricism** [comment]
This will be added in one of the next next script releases, as there are a few additional things that will be added along with this and I want to implement them all at once.
