### ISSUE TITLE
No ADK Installed, Script Hanging On 'Optimizing The Media File Structure'.

### ISSUE THREAD

**Issue by KedarWolf** [DrEmpiricism/Optimize-Offline#90]
It doesn't continue, just stuck on 'Optimizing The Media File Structure' and gives no option to scroll to my folder with oscdimg.exe saved in it.

**Comment by DrEmpiricism** [comment]
Have you made sure this is not popping up behind the foreground screens?

**Comment by KedarWolf** [comment]
Yes, the window must have been behind something, uninstalled ADK, ran it again, it's fine.
