### ISSUE TITLE
ISO images built, during installation result in "Why did my PC restart?" screen

### ISSUE THREAD

**Issue by HarjitSi** [DrEmpiricism/Optimize-Offline#91]
I've built at least half a dozen images and during the install, end up at a "Why did my PC restart?" screen. When I enter the WiFi information, it just reboots.

I downloaded the ISO from Microsoft's servers using the technique mentioned here:
![image](https://user-images.githubusercontent.com/45951076/59698108-de7de480-91a3-11e9-8104-67163ff33af5.png)

I used the Media Creation tool to save off an ISO but the Optimize-Offline script complained it wasn't a real ISO image.

The log files from the latest run is below. My intention was to get rid of the Metro apps, Defender, keep IE 11 (so that I can download Firefox), minimize telemetry and reporting to Microsoft.

[Optimize-Offline.log](https://github.com/DrEmpiricism/Optimize-Offline/files/3302264/Optimize-Offline.log)
[Registry-Optimizations.log](https://github.com/DrEmpiricism/Optimize-Offline/files/3302265/Registry-Optimizations.log)
[WindowsFeatures.txt](https://github.com/DrEmpiricism/Optimize-Offline/files/3302266/WindowsFeatures.txt)

**Comment by marcosviniciusf17** [comment]
The Media Creation Tool creates install.esd (In the sources folder) which is not supported. you need to convert install.esd to install.wim. 
Other than that, your log reports no errors.

**Comment by HarjitSi** [comment]
@marcosviniciusf17 - thank you for the info. on how to use the ISO file from the Media Creation Tool.

I would greatly appreciate hints / suggestions on how to figure out why the ISO after using Optimize-Offline doesn't work.

**Comment by KedarWolf** [comment]
[https://forums.mydigitallife.net/threads/discussion-windows-10-1903-final-build-18362-30-pc-rp-19h1_release.79259/page-159#post-1526691](url)

Guide for the 1903 ISO what's safe to remove. I use Windows 10 Enterprise. The only thing different from the screenshots is I remove Paint in the first one as it just removes 3DPaint and leaves the normal Paint there. I keep the Calculator and Windows Store because I actually use them.

I make a 18362.1 ISO from the UUP website [https://uupdump.ml/](url) , integrate updates with W10UI from My DigitalLife forums, then use Optimize Offline.

**Comment by HarjitSi** [comment]
@KedarWolf - thank you for the details on MyDigitalLife forum and the links.

I want to download the files from MS's servers and do the modifications on file(s) from there. This way, I know the exact base I started with and where I got it and most importantly, I can recreate it.

I'd be very grateful for ideas on how to debug the cause of the issue(s).

**Comment by KedarWolf** [comment]
The UUP Dump website I linked downloads the official files from the Microsoft servers and makes an ISO.

The mail.ru website is the official files, and if you check the hash of the downloads you can see they are the exact same files as from the Microsoft servers. You cannot download the official ISO from Microsoft without an MSDN subscription.

However, the website below WILL download the 17763 or 18362.30 official ISO directly from the Microsoft servers, it just uses a web script to do so. When you do it you'll see the links to download are direct from Microsoft. You'll not get Windows Enterprise this way though. only Windows Pro and Education etc.

https://tb.rg-adguard.net/public.php

**Comment by DrEmpiricism** [comment]
The 'Why Did My PC Restart' error will happen if you remove a System Application or disable an Optional Feature that is required during the OOBE pass.

Your log shows:

> Removing System Application: Microsoft.AAD.BrokerPlugin
> Removing System Application: Microsoft.BioEnrollment
> Removing System Application: Microsoft.MicrosoftEdgeDevToolsClient
> Removing System Application: Microsoft.MicrosoftEdge
> Removing System Application: Microsoft.PPIProjection
> Removing System Application: Microsoft.Windows.CallingShellApp
> Removing System Application: Microsoft.Windows.CapturePicker
> Removing System Application: Microsoft.Windows.CloudExperienceHost
> Removing System Application: Microsoft.Windows.ContentDeliveryManager
> Removing System Application: Microsoft.Windows.ParentalControls
> Removing System Application: Microsoft.Windows.PeopleExperienceHost
> Removing System Application: Microsoft.Windows.SecHealthUI
> Removing System Application: Microsoft.Windows.SecureAssessmentBrowser
> Removing System Application: Microsoft.Windows.XGpuEjectDialog

I would reduce the amount of System Applications you're removing.  BioEnrollment, MicrosoftEdgeDevToolsClient, MicrosoftEdge, PPIProjection, ContentDeliveryManager, ParentalControls, SecHealthUI and SecureAssessmentBrowser are all safe to remove across versions of Windows 10.

**Comment by KedarWolf** [comment]
Only remove these and you'll be fine. Some you are removing causing the install errors.

The Windows apps you removed on the first screen is fine, is the below system apps other than these causing you the problem.

I'm running Enterprise installed with these removed.

2019-06-19T22:51:41 [INFO]: Removing System Application: Microsoft.AAD.BrokerPlugin
2019-06-19T22:51:44 [INFO]: Removing System Application: Microsoft.BioEnrollment
2019-06-19T22:51:47 [INFO]: Removing System Application: Microsoft.MicrosoftEdgeDevToolsClient
2019-06-19T22:51:50 [INFO]: Removing System Application: Microsoft.MicrosoftEdge
2019-06-19T22:51:53 [INFO]: Removing System Application:Microsoft.Windows.ContentDeliveryManager
2019-06-19T22:51:56 [INFO]: Removing System Application: Microsoft.Windows.CallingShellApp
2019-06-19T22:51:59 [INFO]: Removing System Application: Microsoft.Windows.ParentalControls
2019-06-19T22:52:02 [INFO]: Removing System Application: Microsoft.Windows.PeopleExperienceHost
2019-06-19T22:52:05 [INFO]: Removing System Application: Microsoft.Windows.XGpuEjectDialog
2019-06-19T22:52:08 [INFO]: Removing System Application: Microsoft.XboxGameCallableUI
2019-06-19T22:52:11 [INFO]: Removing System Application: Microsoft.Windows.SecHealthUI

2019-06-19T22:52:30 [INFO]: Removing Windows Capability Package: App.Support.QuickAssist
2019-06-19T22:52:34 [INFO]: Removing Windows Capability Package: Browser.InternetExplorer
2019-06-19T22:52:36 [INFO]: Removing Windows Capability Package: Hello.Face.18330
2019-06-19T22:52:39 [INFO]: Removing Windows Capability Package: Hello.Face.Migration.18330
2019-06-19T22:52:42 [INFO]: Removing Windows Capability Package: MathRecognizer
2019-06-19T22:52:45 [INFO]: Removing Windows Capability Package: Media.WindowsMediaPlayer
2019-06-19T22:52:49 [INFO]: Removing Windows Capability Package: OneCoreUAP.OneSync
2019-06-19T22:52:52 [INFO]: Removing Windows Capability Package: OpenSSH.Client

2019-06-19T22:53:40 [INFO]: Disabling Windows Feature: Printing-XPSServices-Features
2019-06-19T22:53:43 [INFO]: Disabling Windows Feature: WorkFolders-Client
2019-06-19T22:53:46 [INFO]: Disabling Windows Feature: SmbDirect
2019-06-19T22:53:48 [INFO]: Disabling Windows Feature: FaxServicesClientPackage

**Comment by verlain3** [comment]
You cannot remove "Microsoft.Windows.CloudExperienceHost"

It will cause the "Why did my PC restart?" screen you are facing

**Comment by HarjitSi** [comment]
Thank you all!

After trying more "experiments", late yesterday, I was able to get a configuration to work. In looking through my screen captures and log files, it includes / doesn't include what you have suggested. I've attached the log files so others can start there.

@KedarWolf - when I wasn't able to get a configuration to work, I actually recreated your configuration using your screenshots to make sure my initial Windows image and process were sound. Once I confirmed that, since I wanted some things you had removed and tried to remove some things you hadn't removed because there wasn't an explanation of - you need to keep this or you will be hosed <- this is understandable given the complexity, I experimented...

I would greatly appreciate it if you all can take a look and say if I've removed something I will regret later. I plan to use (https://github.com/Disassembler0/Win10-Initial-Setup-Script/) to do some post installation clean up. I'm not confident I can incorporate these into the Optimize-Offline scripts. I hope to "final" image the machine tomorrow. 

Thanks again! Great tool. I've been dreading clean installing Windows and this has eliminated that!

[WindowsFeatures.txt](https://github.com/DrEmpiricism/Optimize-Offline/files/3311225/WindowsFeatures.txt)
[Optimize-Offline.log](https://github.com/DrEmpiricism/Optimize-Offline/files/3311226/Optimize-Offline.log)
[Registry-Optimizations.log](https://github.com/DrEmpiricism/Optimize-Offline/files/3311227/Registry-Optimizations.log)

**Comment by KedarWolf** [comment]
The below can be removed as well.

I have Chrome and/or Firefox install,exe on a separate drive I don't install Windows to, no need for IE.
Math Recognizer is just for advanced Calculator stuff like Sine/Cosine etc. I'll never use.
I don't use SSH or SMB at all.
OneCore is the native mail client, don't use it.
I prefer VLC Player to Media Player.
Print To PDF I use to make PDF's of online receipts etc. using the Print dialogue.
App.Support never needed.
If you don't need Windows Store, Calculator or 3DPaint you can remove them and Windows.Paint. The native Paint will still be there.



2019-06-19T22:52:08 [INFO]: Removing System Application: Microsoft.XboxGameCallableUI

2019-06-19T22:52:30 [INFO]: Removing Windows Capability Package: App.Support.QuickAssist
2019-06-19T22:52:34 [INFO]: Removing Windows Capability Package: Browser.InternetExplorer
2019-06-19T22:52:42 [INFO]: Removing Windows Capability Package: MathRecognizer
2019-06-19T22:52:45 [INFO]: Removing Windows Capability Package: Media.WindowsMediaPlayer
2019-06-19T22:52:49 [INFO]: Removing Windows Capability Package: OneCoreUAP.OneSync
2019-06-19T22:52:52 [INFO]: Removing Windows Capability Package: OpenSSH.Client

2019-06-19T22:53:46 [INFO]: Disabling Windows Feature: SmbDirect

**Comment by marcosviniciusf17** [comment]
@KedarWolf thanks for the recommendation, UUP Downloader is awesome. Now I created the Windows ISO with build 18362.175 and modified it with optimize offline. Great combination.

**Comment by KedarWolf** [comment]
Change the UUP downloader files you use, the .ini file (can't recall the name, I'm on the streetcar right now), the net3fx option to net3fx=1 and it'll integrate the net3fx which I don't think it does using the default options.

**Comment by marcosviniciusf17** [comment]
@KedarWolf I'll check this later, thanks

**Comment by KedarWolf** [comment]
Best way to make Windows 10 18362.175 ISO. Download ESD in the right language here. 

Business has Enterprise.

https://forums.mydigitallife.net/threads/windows-10-esd-repository.59082/page-114#post-1531579

Put ESD in the same folder as the ESD Decrypter, run Decrypter as Admin.

https://github.com/abbodi1406/BatUtil/tree/master/esd-decrypter-wimlib

**Comment by KedarWolf** [comment]
> @KedarWolf I'll check this later, thanks

Change your ConvertConfig.ini file to:

```
[convert-UUP]
AutoStart    =1
AddUpdates   =0
ResetBase    =0
NetFx3       =1
StartVirtual =1
wim2esd      =0
SkipISO      =0
SkipWinRE    =0
ForceDism    =0
RefESD       =0

[create_virtual_editions]
vAutoStart   =1
vDeleteSource=1
vPreserve    =0
vwim2esd     =0
vSkipISO     =0
vAutoEditions=Professional

```
Then run convert-UUP.cmd as Admin, it'll make a Windows Pro only ISO for you with NetFX3 and 18362 has NetFX 4.8.

For Windows Enterprise change to this:

`vAutoEditions=Enterprise
`

**Comment by marcosviniciusf17** [comment]
> > @KedarWolf I'll check this later, thanks
> 
> Change your ConvertConfig.ini file to for Enterprise.
> `
> 
> ```
> [convert-UUP]
> AutoStart    =1
> AddUpdates   =1
> ResetBase    =0
> NetFx3       =0
> StartVirtual =0
> wim2esd      =0
> SkipISO      =0
> SkipWinRE    =0
> ForceDism    =0
> RefESD       =0
> 
> [create_virtual_editions]
> vAutoStart   =1
> vDeleteSource=1
> vPreserve    =0
> vwim2esd     =0
> vSkipISO     =0
> vAutoEditions=Enterprise
> ```
> 
> Then run 'convert-UUP.cmd' as Admin, it'll make a Windows Enterprise only ISO for you with NetFX3 and 18362 has NetFX 4.8.
> 
> `

Thank you very much. It helped a lot.

**Comment by KedarWolf** [comment]
> > > @KedarWolf I'll check this later, thanks
> > 
> > 
> > Change your ConvertConfig.ini file to for Enterprise.
> > `
> > ```
> > [convert-UUP]
> > AutoStart    =1
> > AddUpdates   =1
> > ResetBase    =0
> > NetFx3       =0
> > StartVirtual =0
> > wim2esd      =0
> > SkipISO      =0
> > SkipWinRE    =0
> > ForceDism    =0
> > RefESD       =0
> > 
> > [create_virtual_editions]
> > vAutoStart   =1
> > vDeleteSource=1
> > vPreserve    =0
> > vwim2esd     =0
> > vSkipISO     =0
> > vAutoEditions=Enterprise
> > ```
> > 
> > 
> > Then run 'convert-UUP.cmd' as Admin, it'll make a Windows Enterprise only ISO for you with NetFX3 and 18362 has NetFX 4.8.
> > `
> 
> Thank you very much. It helped a lot.
It was supposed to be: 

`NetFx3       =1`

**Comment by marcosviniciusf17** [comment]
@KedarWolf Yes, I realised. I read your configs and compared the documentation. It helped me understand.

**Comment by DrEmpiricism** [comment]
I believe the Math Recognizer package is only applicable to tablets.

**Comment by HarjitSi** [comment]
Did a couple more passes with removing applications. Here are the log files from a configuration that works well for me. This includes the Microsoft (or is it Windows?) Store, doesn't include any Microsoft browsers, Windows (Microsoft?) Defender, Mixed Reality stuff, most XBox stuff (seems some of it is necessary for the store), no OCR, text to speech, etc. The exact features / capabilities can be determined from the log files and the configuration pdf file below.

[Registry-Optimizations.log](https://github.com/DrEmpiricism/Optimize-Offline/files/3318421/Registry-Optimizations.log)
[WindowsFeatures.txt](https://github.com/DrEmpiricism/Optimize-Offline/files/3318422/WindowsFeatures.txt)
[Optimize-Offline.log](https://github.com/DrEmpiricism/Optimize-Offline/files/3318423/Optimize-Offline.log)

Also attached is a PDF file that has images of this script's user interface with the selections I used.
[Optimize-Offline-Configuration.pdf](https://github.com/DrEmpiricism/Optimize-Offline/files/3318426/Optimize-Offline-Configuration.pdf)

I use this along with: https://github.com/Disassembler0/Win10-Initial-Setup-Script/ which I use to do some more tweaks.

**HUGE THANKS** to the author of this script and the folks who helped me get it working and decrapify Windows.

**Comment by KedarWolf** [comment]
> Did a couple more passes with removing applications. Here are the log files from a configuration that works well for me. This includes the Microsoft (or is it Windows?) Store, doesn't include any Microsoft browsers, Windows (Microsoft?) Defender, Mixed Reality stuff, most XBox stuff (seems some of it is necessary for the store), no OCR, text to speech, etc. The exact features / capabilities can be determined from the log files and the configuration pdf file below.
> 
> [Registry-Optimizations.log](https://github.com/DrEmpiricism/Optimize-Offline/files/3318421/Registry-Optimizations.log)
> [WindowsFeatures.txt](https://github.com/DrEmpiricism/Optimize-Offline/files/3318422/WindowsFeatures.txt)
> [Optimize-Offline.log](https://github.com/DrEmpiricism/Optimize-Offline/files/3318423/Optimize-Offline.log)
> 
> Also attached is a PDF file that has images of this script's user interface with the selections I used.
> [Optimize-Offline-Configuration.pdf](https://github.com/DrEmpiricism/Optimize-Offline/files/3318426/Optimize-Offline-Configuration.pdf)
> 
> I use this along with: https://github.com/Disassembler0/Win10-Initial-Setup-Script/ which I use to do some more tweaks.
> 
> **HUGE THANKS** to the author of this script and the folks who helped me get it working and decrapify Windows.

You can deselect anything in Optimize Offline by holding the CTRL key, then clicking on it. That one where you had to select something.
