### ISSUE TITLE
As it's already possible to integrate the Store into LTSC build and Win32 Calc into normal Win10 builds, please also consider adding the ability to integrate the "Developer Mode" capability package.

### ISSUE THREAD

**Issue by Hyperyia** [DrEmpiricism/Optimize-Offline#93]
```
REG ADD "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock" /t REG_DWORD /f /v "AllowDevelopmentWithoutDevLicense" /d "1" 

DISM /Online /Add-Capability /CapabilityName:Tools.DeveloperMode.Core~~~~0.0.1.0
```
![image](https://user-images.githubusercontent.com/32967354/60651750-21e47e00-9e47-11e9-80c1-1529600c7395.png)

**Comment by DrEmpiricism** [comment]
Good idea.

**Comment by DrEmpiricism** [comment]
Adding this capability requires the system to be in an online state so it can download the source package files for it using Windows Update.  The only way this can be added offline is by supplying the source package files for it and these are not publicly available like, for example. the .NET Framework 3 payload packages.

**Comment by Hyperyia** [comment]
> Adding this capability requires the system to be in an online state so it can download the source package files for it using Windows Update. The only way this can be added offline is by supplying the source package files for it and these are not publicly available like, for example. the .NET Framework 3 payload packages.

I found those FOD .cab packages at uupdump.ml, that site gathers the files from Microsoft, so it's safe and trusted source, just like tb.rg-adguard.net for Microsoft Store packages.

https://uupdump.ml/findfiles.php?id=8940db4a-3386-48e8-8793-cbc0b27c695e&q=microsoft-onecore-developermode-desktop-package-amd64.cab
>c04d2520354c332bacda34b997bd69e08947bf54 *microsoft-onecore-developermode-desktop-package-amd64.cab

I believe it should be possible to integrate offline.

**Comment by DrEmpiricism** [comment]
The only way I have been able to get this integrated offline is via my server and deploying the image with MDT.
