### ISSUE TITLE
Get-WindowsCapability : The process cannot access the file because it is being used by another process.

### ISSUE THREAD

**Issue by MajkelP** [DrEmpiricism/Optimize-Offline#94]
Hello! First of all - thank you for great tool.
I would like ask for help, I am using Windows 10 1903  18362.30 Enterprise iso I followed the instruction and I am getting one error:  

Get-WindowsCapability : The process cannot access the file because it is being used by another process.

At C:\Users\Michael\Desktop\Optimize-Offline-master\Optimize-Offline.ps1:699 char:22
+     $GetCapability = Get-WindowsCapability -Path $MountFolder | Where ...
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-WindowsCapability], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.GetWindowsCapabilityCommand
 

 
Could you please explain what is the problem? 

Thank you
M.P

**Comment by DrEmpiricism** [comment]
Something else outside of the script is interacting with the image's mount path.

**Comment by MajkelP** [comment]
For test I installed on virtual machine fresh  Windows 10 Enterprise LTSC and I am getting the same error. I did not install any office, firewall, antivirus.  

Get-WindowsCapability : The process cannot access the file because it is being used by 
another process.

At C:\Optimize-Offline-master\Optimize-Offline.ps1:699 char:22
+     $GetCapability = Get-WindowsCapability -Path $MountFolder | Where ...
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-WindowsCapability], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.GetWindowsCapabilityCommand

I will be trying....

**Comment by DrEmpiricism** [comment]
That error happens because some processes will 'lock' a file or path if it's interacting with it.  For example, Notepad.exe is notorious for doing this and causing said error. For folders or directories, permission changes or using the 'Share' feature can lock them.

I have manually replicated this error by accessing the offline registry hives in regedit while the script has tried to return or remove packages.

**Comment by KedarWolf** [comment]
I had an issue with a similar script where having Windows Explorer file manager open with Preview and Navigation panes enabled it showed in the Preview pane the mounted wim directories and it caused the script to fail with a DISM access file in use error when mounting and unmounting the wims.

I closed Explorer while the app was running, problem solved. Try closing everything but the script, maybe even CTRL ALT DEL and close anything running.

**Comment by MajkelP** [comment]
Thank you for all replays, I will try.

**Comment by MajkelP** [comment]
I closed **explorer process** and script run smoothly. Thank you for guiding me.
