### ISSUE TITLE
Request to add OS metadata to final export folder

### ISSUE THREAD

**Issue by Phatastik** [DrEmpiricism/Optimize-Offline#98]
It is helpful to me (and maybe others) to keep track of different OS builds and script tests if more build details are automatically added to the final export folder name.
Please consider adding to the 'Save' section of Functions.psm1 the full year and other metadata:
Suggested code change after "Optimize-Offline" in line 144 of Version: 3.2.6.1's Functions.psm1
`_[$($ScriptVersion)]-[$($WimImage.Build)]-[$($WimImage.ImageName)]-[$((Get-Date).ToString('MM.dd.yyyy hh.mm.ss')`

**Comment by DrEmpiricism** [comment]
I will just add a separate file that will export a custom object of the image that was optimized with all pertinent metadata included.

**Comment by Phatastik** [comment]
Sounds good, thanks!

**Comment by Phatastik** [comment]
Thanks for metadata export WimFileInfo.txt
Issue closed as far as I'm concerned.
