### ISSUE TITLE
Not An Issue, But Might Want To Follow This Thread

### ISSUE THREAD

**Issue by KedarWolf** [DrEmpiricism/Optimize-Offline#99]
https://forums.mydigitallife.net/threads/optimize-offline-guide-best-windows-debloating-tool-for-17763-ltsc-2019-and-18362-isos.80038/

Might want to Watch this, your advice would be invaluable.

**Comment by DrEmpiricism** [comment]
I glanced at it, but do not have the time to answer questions there that have either been answered here, or are addressed in the ReadMe. People do private message me regularly there about this script (and others) which is fine.

I will check it out when I have the time and I'm browsing those forums but I just do not have the time to offer support in two separate places.
